// The real-stack journey (Task 4.5, slice 4.5e2): one persona, one case, one
// LITE run, driven through the real edge and the real API -- no fixture, no
// demo mode. `tests/journey/run.py` brings up `compose.smoke.yaml`'s
// disposable stack with the deterministic journey worker and starts the test
// edge (`tests/journey/edge.py`) on this config's `baseURL` before this file
// ever runs, and tears both down afterwards; this file only ever talks to
// that edge, the way a browser in production only ever talks to the
// operator's edge.
//
// Serial and shared: every test after the first two builds on the case, run,
// route and gate state the earlier ones left behind, on one `Page` created in
// `beforeAll` rather than the per-test default -- the same pattern
// `tests/journey/run.py`'s own state (the edge's login session, the stack's
// containers) already uses, because this journey *is* one continuous session.
import { execFile } from "node:child_process";
import { randomUUID } from "node:crypto";
import http from "node:http";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import {
  expect,
  test,
  type APIResponse,
  type Browser,
  type BrowserContext,
  type Page,
} from "@playwright/test";

const execFileAsync = promisify(execFile);

const REPO_ROOT = path.resolve(fileURLToPath(new URL(".", import.meta.url)), "..", "..", "..");
const COMPOSE_FILE = path.join(REPO_ROOT, "compose.smoke.yaml");
const PROJECT = "caos-workbench-smoke";
const PYTHON = path.join(REPO_ROOT, ".venv", "bin", "python");

const ANALYST_USER_ID = "6a0e1c2d-0000-4000-8000-00000000a001";
// The other three identities `tests/journey/edge.py` can assert, and which of
// them each governed act of Task 12.5's half of the journey is made by: the
// analyst signs (it created the case, so it holds ADMIN), the approver freezes
// and the filer files, because `APPROVER_NOT_INDEPENDENT` demands three
// different people. The reader is granted and then revoked.
const APPROVER_USER_ID = "6a0e1c2d-0000-4000-8000-00000000a002";
const READER_USER_ID = "6a0e1c2d-0000-4000-8000-00000000a004";
const FILER_USER_ID = "6a0e1c2d-0000-4000-8000-00000000a005";
const TEXT_NAME = "journey-earnings-update.txt";
const PDF_NAME = "journey-covenant-certificate.pdf";
// A draft this surface can actually compose: one paragraph per line, prose
// only, and not one ASCII digit anywhere in it. `revisions.py::_span` refuses
// a digit `NARRATIVE_FIGURE_UNREFERENCED` and tells the author to insert the
// figure through a validated reference, which the Report surface offers no
// picker for -- so a draft written here is a draft written around that.
const DRAFT = [
  "The covenant certificate states headroom rather than leaving it to be inferred.",
  "The earnings update and the certificate disagree, and the disagreement is recorded here rather than resolved.",
].join("\n");
const DIGIT_DRAFT = "Net leverage was 4 times, within the covenant level.";
const QUOTE = "Total debt at 31 December 2026";
const ISSUER_ID = "JOURNEY-HOLDINGS";
const ISSUER_NAME = "Journey Holdings";
const REPORTING_PERIOD = "FY2026 Q2";
const ANALYSIS_DATE = "2026-09-14";
const ROUTE_NODES = ["CP-0", "CP-L10", "CP-5"] as const;
const EDGE_ORIGIN = "http://127.0.0.1:18080";

interface PackFile {
  name: string;
  mimeType: string;
  buffer: Buffer;
}

/** The exact bytes `journey.worker.completions_for` will hash and expect
    among the run's pinned live sources -- generated by calling the same
    `journey.pack` builder the worker calls, never re-implemented here byte
    for byte, so admission and the worker's answer always agree. */
async function packFrom(builder: "journey_pack" | "insufficient_pack"): Promise<PackFile[]> {
  const { stdout } = await execFileAsync(
    PYTHON,
    [
      "-c",
      "import base64, json\n" +
        `from journey.pack import ${builder} as build\n` +
        "print(json.dumps([[n, base64.b64encode(b).decode()] for n, b in build()]))\n",
    ],
    {
      cwd: REPO_ROOT,
      env: {
        ...process.env,
        PYTHONPATH: `${path.join(REPO_ROOT, "tests")}${path.delimiter}${REPO_ROOT}`,
      },
    },
  );
  const rows: [string, string][] = JSON.parse(stdout);
  return rows.map(([name, b64]) => ({
    name,
    mimeType: name.endsWith(".pdf") ? "application/pdf" : "text/plain",
    buffer: Buffer.from(b64, "base64"),
  }));
}

/** The mixed text-and-PDF pack the journey's first case admits. */
const journeyPack = () => packFrom("journey_pack");

/** The deliberately insufficient pack (`docs/REPAIR_PLAN.md` Phase 6): one
    earnings note and no covenant certificate, which the journey worker
    answers with a validated CP-5 `Blocked`. */
const insufficientPack = () => packFrom("insufficient_pack");

/** Restarts one `compose.smoke.yaml` service in place, using the same
    project and compose file `tests/journey/run.py` brought the stack up
    with; the environment it needs (`CAOS_EDGE_TOKEN`, `JOURNEY_STATE_DIR`,
    …) is already this process's own, inherited from that same script. */
async function composeService(...args: string[]): Promise<void> {
  await execFileAsync(
    "docker",
    ["compose", "-p", PROJECT, "-f", COMPOSE_FILE, "--profile", "journey", ...args],
    { cwd: REPO_ROOT },
  );
}

function restartService(service: string): Promise<void> {
  return composeService("restart", service);
}

/** Take the worker away, and give it back. Used by Task 12.5's withdrawal
    test to hold a started run genuinely mid-run: the run is RUNNING and
    queued, its route is pinned and its gates are released, and nothing has
    claimed it -- which is the only state in which "a withdrawal prevents
    *fresh* acceptance" can be asserted rather than raced against a
    deterministic worker that finishes a three-node LITE route in seconds. */
function stopJourneyWorker(): Promise<void> {
  return composeService("stop", "journey-worker");
}

function startJourneyWorker(): Promise<void> {
  return composeService("start", "journey-worker");
}

/** `JOURNEY_EXIT_AFTER_FIRST_ACCEPT` (Task 4.5 decision 12) has already made
    the worker exit(137) once, and nothing in `compose.smoke.yaml` restarts
    it on its own. */
function restartJourneyWorker(): Promise<void> {
  return restartService("journey-worker");
}

type PersonaName = "analyst" | "approver" | "filer" | "reader" | "intruder";

async function loginAs(page: Page, persona: PersonaName): Promise<void> {
  const response = await page.request.get(`/_edge/login?persona=${persona}`);
  expect(response.status()).toBe(200);
}

/** A second browser context logged in as `persona`, because the edge's session
    cookie is one name per context: a persona opened on the shared page's own
    context would clobber the analyst session the rest of this file depends on.
    The caller closes the context it is handed. */
async function contextAs(
  browser: Browser,
  persona: PersonaName,
): Promise<{ context: BrowserContext; page: Page }> {
  const context = await browser.newContext({ baseURL: EDGE_ORIGIN });
  const page = await context.newPage();
  await loginAs(page, persona);
  return { context, page };
}

/** One governed POST from a logged-in page's own session, carrying exactly
    what the workspace's own `fetch` carries: the intent key, and the
    same-origin markers the edge guard demands of an unsafe method (decision
    5). Used where the workspace has no control to press -- the membership
    commands, which `ActionName` deliberately does not carry, and the *first*
    save, which no path in the workspace can reach (see that test's comment). */
function postAs(page: Page, url: string, data: object) {
  return page.request.post(url, {
    data,
    headers: {
      "Idempotency-Key": randomUUID(),
      Origin: EDGE_ORIGIN,
      "Sec-Fetch-Site": "same-origin",
      accept: "application/json",
    },
  });
}

function nodeLocator(page: Page, moduleId: string) {
  return page.locator(`button.node[data-node='${moduleId}']`);
}

/** Polls for a node's state over the run API directly, not by trusting the
    open SSE tail to repaint the DOM and not by reloading the page every
    cycle: the real stream stays connected (confirmed against the network
    trace) while the run genuinely progresses server-side, but a live-push
    repaint is not something this journey depends on to prove the run
    finished. An earlier version reloaded the whole page every 2s, which
    opens a fresh `/events` SSE connection per reload -- the API's SSE tail
    holds a connection until `TAIL_DEADLINE` (300s) even after the client has
    navigated away, with nothing checking for an earlier disconnect, so over
    a 320s wait that piled up abandoned connections past the API's own
    `--limit-concurrency 32` (Dockerfile) and answered later requests, in this
    test and the next one, with a bare 503. Polling the JSON directly opens
    and closes one short-lived request per cycle instead, then reloads once
    at the end to sync the DOM for the assertions that follow. */
interface RunRead {
  status: string;
  nodes: { route_node_id: string; module_id: string; state: string }[];
  /** The `run_work` row, absent until the run is enqueued. No section renders
      it, which is why Task 12.5 reads it from the document the browser itself
      holds rather than from a selector -- see that test's own comment. */
  work: { state: string; stop_code: string | null } | null;
}

/** One short-lived read of the run document's `run`, or `undefined` when
    the read was slow, refused or unparsable -- "not yet", never a hang. */
async function readRun(page: Page, caseId: string, runId: string): Promise<RunRead | undefined> {
  try {
    const response = await page.request.get(`/api/v1/cases/${caseId}/run?run=${runId}`, {
      timeout: 10_000,
    });
    if (!response.ok()) return undefined;
    const body = (await response.json()) as { body: { run: RunRead | null } };
    return body.body.run ?? undefined;
  } catch {
    return undefined;
  }
}

async function waitForNode(
  page: Page,
  caseId: string,
  runId: string,
  moduleId: string,
  state: string,
  timeoutMs: number,
): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  let current: string | undefined;
  for (;;) {
    const run = await readRun(page, caseId, runId);
    current = run?.nodes.find((n) => n.module_id === moduleId)?.state;
    if (current === state) break;
    if (Date.now() >= deadline) {
      throw new Error(
        `${moduleId} did not reach ${state} within ${timeoutMs}ms (last: ${current})`,
      );
    }
    await page.waitForTimeout(2_000);
  }
  // Sync the visible DOM once the API confirms the state, retrying the
  // reload itself since a request right after a long wait can still meet a
  // transient 503 while other abandoned connections from this same wait
  // drain.
  await expect(async () => {
    await page.reload({ timeout: 10_000 });
    await expect(nodeLocator(page, moduleId)).toHaveAttribute("data-state", state, {
      timeout: 10_000,
    });
  }).toPass({ timeout: 30_000 });
}

/** Polls the run's own status the way `waitForNode` polls a node's, then
    reloads once so the DOM the assertions read is the state the API confirmed. */
async function waitForRunStatus(
  page: Page,
  caseId: string,
  runId: string,
  status: string,
  timeoutMs: number,
): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  let current: string | undefined;
  for (;;) {
    current = (await readRun(page, caseId, runId))?.status;
    if (current === status) break;
    if (Date.now() >= deadline) {
      throw new Error(`run did not reach ${status} within ${timeoutMs}ms (last: ${current})`);
    }
    await page.waitForTimeout(2_000);
  }
  await expect(async () => {
    await page.reload({ timeout: 10_000 });
    await expect(page.locator("dt:text-is('Status') + dd")).toContainText(status, {
      timeout: 10_000,
    });
  }).toPass({ timeout: 30_000 });
}

/** The receipt of a command that must have been accepted, and the typed
    refusal in the failure when it was not: a bare status comparison says 400
    and not which rule refused, which is the whole of what a reader of a red
    journey needs. The body is the host's `{code, clears}`, never anything a
    document supplied. */
async function receipt<R>(response: APIResponse, status: number): Promise<R> {
  const body = (await response.json()) as R;
  if (response.status() !== status) {
    throw new Error(`refused ${response.status()}: ${JSON.stringify(body)}`);
  }
  return body;
}

/** Create a case through the case register and return its id, exactly as the
    two tests that predate this helper do it. */
async function createCase(page: Page, title: string): Promise<string> {
  await page.goto("/directory/");
  await page.getByLabel("New case title").fill(title);
  await page.locator("[data-new-case] [aria-label='Create case']").click();
  const success = page.locator("[data-new-case-success]");
  await expect(success).toBeVisible();
  const text = (await success.textContent()) ?? "";
  const found = text.match(/Case ([0-9a-f-]{36}) created\./);
  if (!found) throw new Error(`case id not found in: ${text}`);
  const caseId = found[1] ?? "";
  expect(caseId).not.toBe("");
  return caseId;
}

/** Admit `pack` on the open Upload section and expect all of it in. */
async function admit(page: Page, caseId: string, pack: PackFile[]): Promise<void> {
  await page.goto(`/upload/?case=${caseId}`);
  await page
    .locator("[data-admit-sources] input[type=file]")
    .setInputFiles(
      pack.map((file) => ({ name: file.name, mimeType: file.mimeType, buffer: file.buffer })),
    );
  await page.locator("[data-admit-sources] [aria-label='Admit sources']").click();
  await expect(page.locator("[data-admit-sources-success]")).toContainText(
    `${pack.length} source(s) admitted.`,
  );
}

/** A run of the case, up to the point where only Start is left: the LITE
    route selected and pinned, the subject pinned, both gates previewed and
    released. The same sequence tests 2 and 3 make, so a third case does not
    write it out a third time. Returns the new run's id. */
async function prepareRun(page: Page, caseId: string): Promise<string> {
  await page.goto(`/run/?case=${caseId}`);
  await page.locator("[data-route-select]").selectOption({
    label: "LITE_CREDIT_22 · LITE_EARNINGS_UPDATE",
  });
  await Promise.all([
    page.waitForResponse(
      (response) =>
        response.request().method() === "POST" &&
        new URL(response.url()).pathname === `/api/v1/cases/${caseId}/runs` &&
        response.status() === 201,
    ),
    page.locator("[data-create-run] [data-action='CREATE_RUN']").click(),
  ]);
  await expect(page.locator("[data-run]")).toBeVisible({ timeout: 15_000 });
  const runId = (await page.locator("[data-run]").getAttribute("data-run")) ?? "";
  expect(runId).not.toBe("");
  await page.locator("[data-pin-input] input[data-field='issuer_id']").fill(ISSUER_ID);
  await page.locator("[data-pin-input] input[data-field='issuer_name']").fill(ISSUER_NAME);
  await page
    .locator("[data-pin-input] input[data-field='reporting_period']")
    .fill(REPORTING_PERIOD);
  await page.locator("[data-pin-input] input[data-field='analysis_date']").fill(ANALYSIS_DATE);
  await page.locator("[data-pin-input] [data-action='PIN_RUN_INPUT']").click();
  await expect(page.locator("[data-pin-input] [data-command-success]")).toContainText(
    "Subject pinned.",
  );
  for (const gate of ["SOURCE_SET", "RESEARCH_PLAN"] as const) {
    const panel = page.locator(`[data-gate-panel='${gate}']`);
    await panel.locator(`[data-preview-gate='${gate}']`).click();
    await expect(panel.locator("[data-gate-preview-content]")).not.toBeEmpty();
    await panel
      .locator(`[data-action='APPROVE_SOURCE_SET'], [data-action='APPROVE_RESEARCH_PLAN']`)
      .click();
    await expect(panel).toContainText("RELEASED", { timeout: 15_000 });
  }
  return runId;
}

/** A tiny HTTP server on its own ephemeral port -- a different origin from
    the edge on any browser's same-site rules -- serving one page that fires
    a cross-site, no-preflight ("simple request") POST at `target` the moment
    it loads. `text/plain` is CORS-safelisted, so the browser sends it with
    no permission check; whether it *changes* anything is exactly what
    decision 5's Origin / `Sec-Fetch-Site` check and `SameSite=Lax` on the
    edge's cookie are there to refuse. */
async function serveCrossSitePost(
  targetUrl: string,
  body: string,
): Promise<{ url: string; close: () => Promise<void> }> {
  const html =
    "<!doctype html><body><script>" +
    `fetch(${JSON.stringify(targetUrl)}, { method: "POST", mode: "no-cors", credentials: "include",` +
    ` headers: { "Content-Type": "text/plain" }, body: ${JSON.stringify(body)} })` +
    ".finally(() => { document.title = 'sent'; });" +
    "</script></body>";
  const server = http.createServer((_req, res) => {
    res.writeHead(200, { "content-type": "text/html" });
    res.end(html);
  });
  await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
  const address = server.address();
  if (address === null || typeof address === "string") throw new Error("no ephemeral port");
  return {
    url: `http://127.0.0.1:${address.port}/`,
    close: () => new Promise<void>((resolve) => server.close(() => resolve())),
  };
}

test.describe.serial("journey", () => {
  let page: Page;
  let caseId = "";
  let runId = "";
  // Task 12.5's own state: the withdrawal case and the run of it that was
  // started and then had its evidence taken away, and the head revision of
  // the first case the filing chain acts on.
  let withdrawalCase = "";
  let withdrawalRun = "";
  let revisionId = "";
  let payloadSha256 = "";

  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
    await loginAs(page, "analyst");
    // Fails in seconds, not the full test timeout, when the edge or the API
    // is misconfigured (a stale edge token, a port collision with a leftover
    // process, …): the very first navigation must not read back a refusal
    // body instead of the workspace.
    await page.goto("/directory/");
    await expect(page.getByText("EDGE_NOT_TRUSTED")).toHaveCount(0, { timeout: 15_000 });
    await expect(page.locator("[data-new-case]")).toBeVisible({ timeout: 15_000 });
  });

  test.afterAll(async () => {
    await page.close();
  });

  test("journey: create a case and admit a mixed text and PDF pack", async () => {
    const title = `Journey ${randomUUID()}`;
    await page.goto("/directory/");
    await page.getByLabel("New case title").fill(title);
    await page.locator("[data-new-case] [aria-label='Create case']").click();
    const success = page.locator("[data-new-case-success]");
    await expect(success).toBeVisible();
    const text = (await success.textContent()) ?? "";
    const found = text.match(/Case ([0-9a-f-]{36}) created\./);
    if (!found) throw new Error(`case id not found in: ${text}`);
    caseId = found[1] ?? "";
    expect(caseId).not.toBe("");
    await expect(page.locator(`[data-case='${caseId}']`)).toContainText(title);

    await page.goto(`/upload/?case=${caseId}`);
    const pack = await journeyPack();
    await page
      .locator("[data-admit-sources] input[type=file]")
      .setInputFiles(
        pack.map((file) => ({ name: file.name, mimeType: file.mimeType, buffer: file.buffer })),
      );
    await page.locator("[data-admit-sources] [aria-label='Admit sources']").click();
    await expect(page.locator("[data-admit-sources-success]")).toContainText(
      "2 source(s) admitted.",
    );
    await expect(page.locator("[data-source-pack] tbody tr")).toHaveCount(2);
  });

  test("journey: select the LITE route and pin the subject", async () => {
    await page.goto(`/run/?case=${caseId}`);
    // Every enabled pathway is offered, counted explicitly: deploying one
    // should cost a deliberate edit here rather than passing unnoticed.
    await expect(page.locator("[data-route-select] option")).toHaveCount(3);
    await expect(
      page.locator("[data-route-select] option", {
        hasText: "LITE_CREDIT_22 · LITE_EARNINGS_UPDATE",
      }),
    ).toHaveCount(1);
    await page.locator("[data-route-select]").selectOption({
      label: "LITE_CREDIT_22 · LITE_EARNINGS_UPDATE",
    });
    // Creation is not idempotent: retrying the click can create a second run
    // while the worker claims the first, splitting this shared journey's
    // observed run from its executed run. A transient command failure must
    // fail this fresh-stack journey rather than silently changing its subject.
    await Promise.all([
      page.waitForResponse(
        (response) =>
          response.request().method() === "POST" &&
          new URL(response.url()).pathname === `/api/v1/cases/${caseId}/runs` &&
          response.status() === 201,
      ),
      page.locator("[data-create-run] [data-action='CREATE_RUN']").click(),
    ]);
    await expect(page.locator("[data-run]")).toBeVisible({ timeout: 15_000 });
    runId = (await page.locator("[data-run]").getAttribute("data-run")) ?? "";
    expect(runId).not.toBe("");

    await page.locator("[data-pin-input] input[data-field='issuer_id']").fill(ISSUER_ID);
    await page.locator("[data-pin-input] input[data-field='issuer_name']").fill(ISSUER_NAME);
    await page
      .locator("[data-pin-input] input[data-field='reporting_period']")
      .fill(REPORTING_PERIOD);
    await page.locator("[data-pin-input] input[data-field='analysis_date']").fill(ANALYSIS_DATE);
    await page.locator("[data-pin-input] [data-action='PIN_RUN_INPUT']").click();
    await expect(page.locator("[data-pin-input] [data-command-success]")).toContainText(
      "Subject pinned.",
    );
  });

  test("journey: preview and approve the source-set and research-plan gates", async () => {
    for (const gate of ["SOURCE_SET", "RESEARCH_PLAN"] as const) {
      const panel = page.locator(`[data-gate-panel='${gate}']`);
      await expect(panel).toBeVisible();
      await panel.locator(`[data-preview-gate='${gate}']`).click();
      await expect(panel.locator("[data-gate-preview-content]")).not.toBeEmpty();
      const approve = panel.locator(
        `[data-action='APPROVE_SOURCE_SET'], [data-action='APPROVE_RESEARCH_PLAN']`,
      );
      await approve.click();
      await expect(panel).toContainText("RELEASED", { timeout: 15_000 });
    }
    const pinned = await page.evaluate(
      () => document.querySelector("[data-work-controls]") !== null,
    );
    expect(pinned).toBe(true);
  });

  test("journey: start the run and the worker completes it after one kill and restart", async () => {
    await page.locator("[data-work-controls] [data-action='START_RUN']").click();
    await expect(page.locator("[data-work-controls] [data-command-success]")).toContainText(
      "Run enqueued.",
    );

    if (process.env.JOURNEY_FAST === "1") {
      // Local iteration only, never the real gate: `run.py` always forces
      // `JOURNEY_EXIT_AFTER_FIRST_ACCEPT=1`, so reaching this branch means a
      // developer ran the stack by hand with that unset -- the worker never
      // exits, so every node completes without the real kill or the 300 s
      // lease wait below. The final chromium run and the final three-engine
      // run must never set `JOURNEY_FAST`.
      await waitForNode(page, caseId, runId, "CP-0", "COMPLETE", 60_000);
      await waitForNode(page, caseId, runId, "CP-L10", "COMPLETE", 60_000);
      await waitForNode(page, caseId, runId, "CP-5", "COMPLETE", 60_000);
    } else {
      // The journey worker exits(137) right after its first acceptance
      // (decision 12); the frontier's first node is CP-0, so its acceptance
      // is what the exit waits for.
      await waitForNode(page, caseId, runId, "CP-0", "COMPLETE", 120_000);
      await restartJourneyWorker();
      // The crashed process's work lease (`server/store/work.py`'s
      // `LEASE_SECONDS = 300`) is not released early -- CLAUDE.md's Phase 2
      // ledger entry "A stale lease holder can still pay once" is exactly
      // this: nothing reclaims a lease before it naturally expires, so the
      // restarted container (a new process, a new worker identity) cannot
      // claim CP-L10 until the original lease's 300 s run out. This wait is
      // that real architectural pause, not a margin for slowness.
      await waitForNode(page, caseId, runId, "CP-L10", "COMPLETE", 320_000);
      await waitForNode(page, caseId, runId, "CP-5", "COMPLETE", 60_000);
    }
    await expect(page.locator("dt:text-is('Status') + dd")).toContainText("COMPLETE", {
      timeout: 30_000,
    });
  });

  test("a stale view holds its figures until Reload", async () => {
    // A second run, created but never pinned or started, becomes the case's
    // latest -- the SSE tail still open on this page refetches on every
    // event this creates, and the figures shown stay run 1's regardless,
    // because they are bound to the `run` query this page was opened with,
    // not to whichever run is now latest. Only navigating to a different
    // `run` -- the one act "Reload" stands for here -- would show run 2's.
    const before = await page.locator("[data-run]").getAttribute("data-run");
    await Promise.all([
      page.waitForResponse(
        (response) =>
          response.request().method() === "POST" &&
          new URL(response.url()).pathname === `/api/v1/cases/${caseId}/runs` &&
          response.status() === 201,
      ),
      page.locator("[data-create-run] [data-action='CREATE_RUN']").click(),
    ]);
    // The API's own `--limit-concurrency 32` (Dockerfile) can answer a
    // request with a bare 503 "Service Unavailable" while the reload-driven
    // polling above (test 4's 300 s lease wait) still has connections
    // draining -- a transient real-server condition, not this page's fault,
    // so retry the navigation the same way `waitForNode` tolerates a slow
    // repaint.
    await expect(async () => {
      await page.goto(`/run/?case=${caseId}&run=${runId}`);
      await expect(page.locator("[data-stale-run]")).toBeVisible({ timeout: 5_000 });
    }).toPass({ timeout: 30_000 });
    await expect(page.locator("[data-run]")).toHaveAttribute("data-run", before ?? runId);
    const row = page.locator(`[data-run-row='${runId}']`);
    await expect(row).toHaveAttribute("data-displayed", "true");
    await expect(row).toHaveAttribute("data-latest", "false");
  });

  test("journey: analysis shows labelled source facts, model analysis and limitations", async () => {
    await page.goto(`/analysis/?case=${caseId}&run=${runId}`);
    await expect(page.locator("[data-handoff]")).toHaveCount(3);
    for (const moduleId of ROUTE_NODES) {
      const card = page.locator(`[data-handoff='${moduleId}']`);
      await expect(card).toBeVisible();
      await expect(card.locator("[data-qa-status]")).toContainText("Passed");
      await expect(card.locator("[data-committee-status]")).not.toBeEmpty();
      await expect(card.locator("[data-limitation-flags]")).toBeVisible();
      await expect(card.locator("[data-model-analysis] .model-text")).not.toBeEmpty();
      const facts = card.locator("[data-citation]");
      await expect(facts.first()).toBeVisible();
      await expect(facts.first().locator("blockquote.matched")).toContainText(QUOTE);
    }
  });

  test("the highlight covers the rendered words of the matched text", async () => {
    const card = page.locator("[data-handoff='CP-0']");
    await card.locator("[data-citation] [data-fact-chip]").first().click();
    const drawer = page.locator("[data-evidence-drawer]");
    await expect(drawer).toContainText("Text layer from the token index");
    const line = drawer.locator("[data-page-line]", { hasText: QUOTE });
    const highlight = drawer.locator("[data-highlight]");
    await expect(line).toBeVisible();
    await expect(highlight).toHaveCount(1);
    await expect
      .poll(async () => {
        const words = await line.boundingBox();
        const box = await highlight.boundingBox();
        if (!words || !box) return false;
        // Unlike the workbench's demo fixture (whose quote is a whole line),
        // QUOTE here is only the line's leading words -- "Total debt at 31
        // December 2026" out of "…2026 stood at 1,240 million" -- so the
        // highlight is correctly narrower than the line, not equal to it.
        // What must hold is the shared origin and line height (the same
        // stored rectangle placed the highlight this test opened), and a
        // width that covers a real word span: narrower than the whole line,
        // wider than a sliver.
        return (
          Math.abs(box.x - words.x) <= 4 &&
          Math.abs(box.y - words.y) <= 4 &&
          Math.abs(box.height - words.height) <= 4 &&
          box.width > words.width * 0.3 &&
          box.width < words.width
        );
      })
      .toBe(true);
  });

  test("journey: a reader sees qualification as restricted beside the real PDF evidence", async ({
    browser,
  }) => {
    const readerContext = await browser.newContext({ baseURL: EDGE_ORIGIN });
    const reader = await readerContext.newPage();
    await loginAs(reader, "reader");

    await reader.goto(`/analysis/?case=${caseId}&run=${runId}&qualification=${"a".repeat(64)}`);
    await expect(reader.getByLabel("Qualification")).toContainText("RESTRICTED");
    await expect(reader.getByLabel("Qualification")).toContainText(
      "Qualification metadata requires an analyst role.",
    );
    await readerContext.close();
  });

  test("Escape returns focus to the chip that opened the drawer", async () => {
    const chip = page.locator("[data-handoff='CP-0'] [data-citation] [data-fact-chip]").first();
    await expect(page.getByRole("dialog")).toBeVisible();
    await page.keyboard.press("Escape");
    await expect(page.getByRole("dialog")).toHaveCount(0);
    await expect(chip).toBeFocused();
  });

  test("a dropped stream resumes after its Last-Event-ID", async () => {
    // The tail this page's Analysis view opened is real and open, but by now
    // (several navigations past the run's own completion) it has gone idle:
    // nothing has happened on this case since, so its `EventSource` has no
    // `id:` yet to remember. Admitting one more harmless source (the same
    // pack file again -- content-addressed, so this is a no-op on the store
    // beyond one more row) emits `sources_changed`, which reaches this exact
    // tab's own long-open connection without any navigation of this page to
    // break it -- unlike creating another run, which this test does not need
    // and which would only add another stale-run case already covered above.
    const [firstFile] = await journeyPack();
    if (!firstFile) throw new Error("journey pack is empty");
    const admit = () =>
      page.request.post(`/api/v1/cases/${caseId}/sources`, {
        multipart: {
          document: {
            name: firstFile.name,
            mimeType: firstFile.mimeType,
            buffer: firstFile.buffer,
          },
        },
        // What the page's own fetch carries: the edge guard refuses an
        // unsafe method without a same-origin Origin (decision 5).
        headers: {
          "Idempotency-Key": randomUUID(),
          Origin: EDGE_ORIGIN,
          "Sec-Fetch-Site": "same-origin",
        },
      });
    // The first admission's refetch can move the view onto `?run=`, which
    // reopens its tail at the heads -- a fresh connection that has seen no
    // `id:` yet (Firefox does this; Chromium's timing hides it). The second
    // admission lands on the settled tail, so the connection the restart
    // severs has an id to send back. The server polls every 0.5 s
    // (POLL_INTERVAL); the waits cover that plus the refetch.
    expect((await admit()).status()).toBe(201);
    await page.waitForTimeout(2_000);
    expect((await admit()).status()).toBe(201);
    await page.waitForTimeout(2_000);

    // `EventSource` sends Last-Event-ID only on its own reconnect after the
    // server actually closes the connection -- toggling the browser
    // context's own network state does not touch an already-open socket, so
    // this drops the connection from the server side instead: restarting
    // `api` severs every open connection (including the test edge's proxied
    // one to it), and the browser's automatic reconnect, having consumed the
    // `id:`-bearing event above, sends it back as Last-Event-ID -- real
    // behaviour, not a fixture emulating it.
    const seenLastEventId = page.waitForRequest(
      async (request) =>
        request.url().includes(`/api/v1/cases/${caseId}/events`) &&
        Boolean((await request.allHeaders())["last-event-id"]),
      { timeout: 60_000 },
    );
    await restartService("api");
    await seenLastEventId;
  });

  test("journey: an insufficient-evidence run ends BLOCKED and is shown as such, not as success", async () => {
    // The deliberately restricted case (`docs/REPAIR_PLAN.md` Phase 6 exit
    // check, `docs/FINAL_CHECK.md` item 4): a second case on the same stack
    // whose pack is one earnings note and no covenant certificate. The
    // journey worker keys its answer on the evidence pinned -- this pack's
    // digest gets CP-0 and CP-L10 `Passed` and a validated CP-5 `Blocked` --
    // so the run ends BLOCKED by the route's own rule
    // (`server/engine/runtime.py::_end_blocked`) rather than by an error.
    // What is asserted is what a person sees: the run's status, the case
    // register's tag, and the analysis page holding exactly the two accepted
    // handoffs with CP-5 absent and pending -- never a COMPLETE, never a
    // third handoff.
    const title = `Journey insufficient ${randomUUID()}`;
    await page.goto("/directory/");
    await page.getByLabel("New case title").fill(title);
    await page.locator("[data-new-case] [aria-label='Create case']").click();
    const success = page.locator("[data-new-case-success]");
    await expect(success).toBeVisible();
    const found = ((await success.textContent()) ?? "").match(/Case ([0-9a-f-]{36}) created\./);
    if (!found) throw new Error("case id not found");
    const thinCase = found[1] ?? "";
    expect(thinCase).not.toBe("");

    await page.goto(`/upload/?case=${thinCase}`);
    const pack = await insufficientPack();
    expect(pack).toHaveLength(1);
    await page
      .locator("[data-admit-sources] input[type=file]")
      .setInputFiles(
        pack.map((file) => ({ name: file.name, mimeType: file.mimeType, buffer: file.buffer })),
      );
    await page.locator("[data-admit-sources] [aria-label='Admit sources']").click();
    await expect(page.locator("[data-admit-sources-success]")).toContainText(
      "1 source(s) admitted.",
    );

    await page.goto(`/run/?case=${thinCase}`);
    await page.locator("[data-route-select]").selectOption({
      label: "LITE_CREDIT_22 · LITE_EARNINGS_UPDATE",
    });
    await Promise.all([
      page.waitForResponse(
        (response) =>
          response.request().method() === "POST" &&
          new URL(response.url()).pathname === `/api/v1/cases/${thinCase}/runs` &&
          response.status() === 201,
      ),
      page.locator("[data-create-run] [data-action='CREATE_RUN']").click(),
    ]);
    await expect(page.locator("[data-run]")).toBeVisible({ timeout: 15_000 });
    const thinRun = (await page.locator("[data-run]").getAttribute("data-run")) ?? "";
    expect(thinRun).not.toBe("");
    await page.locator("[data-pin-input] input[data-field='issuer_id']").fill(ISSUER_ID);
    await page.locator("[data-pin-input] input[data-field='issuer_name']").fill(ISSUER_NAME);
    await page
      .locator("[data-pin-input] input[data-field='reporting_period']")
      .fill(REPORTING_PERIOD);
    await page.locator("[data-pin-input] input[data-field='analysis_date']").fill(ANALYSIS_DATE);
    await page.locator("[data-pin-input] [data-action='PIN_RUN_INPUT']").click();
    await expect(page.locator("[data-pin-input] [data-command-success]")).toContainText(
      "Subject pinned.",
    );
    for (const gate of ["SOURCE_SET", "RESEARCH_PLAN"] as const) {
      const panel = page.locator(`[data-gate-panel='${gate}']`);
      await panel.locator(`[data-preview-gate='${gate}']`).click();
      await expect(panel.locator("[data-gate-preview-content]")).not.toBeEmpty();
      await panel
        .locator(`[data-action='APPROVE_SOURCE_SET'], [data-action='APPROVE_RESEARCH_PLAN']`)
        .click();
      await expect(panel).toContainText("RELEASED", { timeout: 15_000 });
    }
    await page.locator("[data-work-controls] [data-action='START_RUN']").click();
    await expect(page.locator("[data-work-controls] [data-command-success]")).toContainText(
      "Run enqueued.",
    );

    // The worker has already exited once on the first case (decision 12) and
    // holds no stale lease on this run, so this takes seconds, not a lease.
    await waitForNode(page, thinCase, thinRun, "CP-L10", "COMPLETE", 120_000);
    await waitForRunStatus(page, thinCase, thinRun, "BLOCKED", 120_000);

    // The run page: BLOCKED, never COMPLETE; the two upstream nodes accepted;
    // CP-5 attempted once and not accepted.
    const status = page.locator("dt:text-is('Status') + dd");
    await expect(status).toContainText("BLOCKED");
    await expect(status).not.toContainText("COMPLETE");
    await expect(nodeLocator(page, "CP-0")).toHaveAttribute("data-state", "COMPLETE");
    await expect(nodeLocator(page, "CP-L10")).toHaveAttribute("data-state", "COMPLETE");
    // CP-5 keeps an unaccepted attempt and, recomputed from accepted artifacts
    // alone, a RUNNABLE state -- both true. What must not follow is the page
    // drawing it as running, or saying it is in the frontier, beside a Status
    // of BLOCKED. Nothing on an ended run is in flight.
    await expect(nodeLocator(page, "CP-5")).not.toHaveClass(/\brunning\b/);
    // And why it ended: CP-5 did run, and its validated Blocked verdict is
    // what ended the run. The document names it (`blocked_by`, §68), and the
    // page says so in three places -- on the node, in its detail, and in the
    // run panel -- instead of listing CP-5 among the nodes that did not run,
    // which read as the opposite of what happened.
    await expect(nodeLocator(page, "CP-5")).toHaveAttribute("data-blocking", "yes");
    await expect(nodeLocator(page, "CP-5")).toContainText("BLOCKED THE RUN");
    await expect(nodeLocator(page, "CP-0")).toHaveAttribute("data-blocking", "no");
    await expect(nodeLocator(page, "CP-L10")).toHaveAttribute("data-blocking", "no");
    await nodeLocator(page, "CP-5").click();
    await expect(page.locator("[data-node-detail='CP-5']")).toBeVisible();
    const detail = page.locator("[data-node-detail='CP-5']");
    await expect(detail).toContainText("answered Blocked · ended the run");
    await expect(detail).not.toContainText("did not run");
    await expect(detail).not.toContainText("in the frontier");
    const attempts = page.locator("section.pnl", { hasText: "Attempts — CP-5" });
    await expect(attempts.locator("[data-attempt]")).toHaveCount(1);
    await expect(attempts.locator("[data-attempt]")).toContainText("BLOCKED · NOT ACCEPTED");
    await expect(attempts.locator("[data-blocking-attempt]")).toHaveCount(1);
    const blockedBy = page.locator("dt:text-is('Blocked by') + dd");
    await expect(blockedBy).toHaveAttribute("data-blocked-by", "CP-5");
    await expect(blockedBy).toContainText("CP-5 answered Blocked on attempt 1");

    // The analysis page: exactly the two accepted handoffs, both citing the
    // thin note; CP-5 has no handoff and is listed as not accepted.
    await page.goto(`/analysis/?case=${thinCase}&run=${thinRun}`);
    // The page carries the run's own status now, so "pending" — a claim about
    // what happens next — is not what it says about a run that has stopped.
    await expect(page.locator("[data-pending]")).toHaveAttribute("data-run-ended", "yes");
    await expect(page.locator("[data-pending]")).toContainText("did not run");
    await expect(page.locator("[data-pending]")).toContainText("the run ended BLOCKED");
    await expect(page.locator("[data-handoff]")).toHaveCount(2);
    await expect(page.locator("[data-handoff='CP-5']")).toHaveCount(0);
    for (const moduleId of ["CP-0", "CP-L10"]) {
      const card = page.locator(`[data-handoff='${moduleId}']`);
      await expect(card.locator("[data-qa-status]")).toContainText("Passed");
      await expect(card.locator("[data-citation] blockquote.matched").first()).toContainText(QUOTE);
    }
    await expect(page.locator("[data-pending-node='CP-5']")).toBeVisible();
    // And which of the three it is: CP-5 answered and ended the run, so it is
    // named here rather than left among the two that never started.
    await expect(page.locator("[data-pending]")).toContainText("the run ended BLOCKED on CP-5");
    await expect(page.locator("[data-pending-node='CP-5']")).toHaveAttribute(
      "data-blocking",
      "yes",
    );
    await expect(page.locator("[data-pending-node='CP-5']")).toContainText(
      "its verdict ended the run",
    );
    await expect(page.locator(".tag.ok", { hasText: "ACCEPTED" })).toHaveText("2 ACCEPTED");

    // The case register names the outcome beside the case.
    await page.goto("/directory/");
    const row = page.locator(`[data-case='${thinCase}']`);
    await expect(row).toContainText(title);
    await expect(row).toContainText("BLOCKED");
    await expect(row).not.toContainText("COMPLETE");
  });

  test("journey: every section deep link loads through the edge with its query", async () => {
    const links: [string, string][] = [
      ["Case register", `/directory/`],
      ["Source pack", `/upload/?case=${caseId}`],
      ["Resolved route", `/run/?case=${caseId}&run=${runId}`],
      ["Handoffs", `/analysis/?case=${caseId}&run=${runId}`],
    ];
    for (const [marker, url] of links) {
      await page.goto(url);
      await expect(page.locator("main#body [data-surface-state='unavailable']")).toHaveCount(0);
      await expect(page.getByText(marker).first()).toBeVisible();
    }
  });

  test("journey: forged identity headers through the edge reach nobody else's case", async ({
    browser,
  }) => {
    // A separate browser context, not just a new tab on `page`'s -- the
    // edge's session cookie is one name per context, and logging in as
    // "intruder" here must never clobber the analyst session every other
    // test in this file depends on.
    const intruderContext = await browser.newContext({ baseURL: EDGE_ORIGIN });
    const intruder = await intruderContext.newPage();
    await loginAs(intruder, "intruder");
    const response = await intruder.request.get(`/api/v1/cases/${caseId}/analysis?run=${runId}`, {
      headers: { "x-caos-user": ANALYST_USER_ID, accept: "application/json" },
    });
    // The edge's own forwarded identity (the intruder's session, decision 2)
    // is what reaches the API; the client's `x-caos-user` is never in the
    // edge's allow-listed pass-through set and never arrives. An actor with
    // no standing on this case is answered exactly as an unknown one would be
    // (CLAUDE.md "Auth edge": unknown and unauthorized both 404).
    expect(response.status()).toBe(404);
    await intruder.goto(`/analysis/?case=${caseId}&run=${runId}`);
    await expect(intruder.locator("main#body [data-surface-state='unavailable']")).toHaveCount(1);
    await expect(intruder.getByText(QUOTE)).toHaveCount(0);
    await intruderContext.close();
  });

  test("journey: a cross-site form post through the edge changes nothing", async ({ browser }) => {
    const sentinel = `csrf-sentinel-${randomUUID()}`;
    const body = JSON.stringify({ title: sentinel });
    const foreign = await serveCrossSitePost(`${EDGE_ORIGIN}/api/v1/cases`, body);
    // `page`'s own context came from `browser.newPage()` in `beforeAll`,
    // which Playwright limits to that one page -- a second tab needs its
    // own context, the same way the intruder persona above does. It carries
    // no cookie, so the "no session" 401 the edge answers with is exactly
    // the point: this attacker page never had the analyst's session either.
    const attackerContext = await browser.newContext();
    try {
      const attacker = await attackerContext.newPage();
      await attacker.goto(foreign.url);
      await expect.poll(() => attacker.title()).toBe("sent");
      await attacker.close();
    } finally {
      await attackerContext.close();
      await foreign.close();
    }
    await page.goto("/directory/");
    await expect(page.locator("table.reg")).not.toContainText(sentinel);
  });

  test("the served policy refuses an injected inline script and the journey records no violation", async () => {
    await page.goto(`/analysis/?case=${caseId}&run=${runId}`);
    await page.evaluate(() => {
      (window as unknown as { __cspViolations: number }).__cspViolations = 0;
      window.addEventListener("securitypolicyviolation", () => {
        (window as unknown as { __cspViolations: number }).__cspViolations += 1;
      });
    });
    await page.evaluate(() => {
      // The served policy's `require-trusted-types-for 'script'; trusted-types
      // 'none'` (decision 5) refuses even the *assignment* here -- Trusted
      // Types guards `HTMLScriptElement.textContent` as a sink, and with no
      // policy named nothing can produce the `TrustedScript` it now demands,
      // so this throws before the element is ever appended. That is a
      // stronger refusal than a script-src violation on an appended element
      // would be, and the point this test proves either way: catch it so the
      // throw itself doesn't fail the read, and let the assertions below
      // confirm the script never ran and the browser still recorded a
      // violation.
      try {
        const script = document.createElement("script");
        script.textContent = "window.__journeyInlineScriptRan = true;";
        document.body.appendChild(script);
      } catch {
        // Refused at assignment, before script-src is ever asked.
      }
    });
    const ran = await page.evaluate(
      () => (window as unknown as { __journeyInlineScriptRan?: boolean }).__journeyInlineScriptRan,
    );
    expect(ran).toBeUndefined();
    const violations = await page.evaluate(
      () => (window as unknown as { __cspViolations: number }).__cspViolations,
    );
    expect(violations).toBeGreaterThan(0);
    // The refused script left no visible trace on the workspace itself: CSP
    // is the browser's own enforcement, and nothing here logs or renders it.
    await expect(page.locator("[data-command-error], [role='alert']")).toHaveCount(0);
  });

  test("journey: withdrawing a live source mid-run prevents fresh acceptance and updates an open drawer", async ({
    browser,
  }) => {
    // Invariant 1's second half, end to end on one case. Two runs of it are
    // needed, because the two halves of the claim are about different things:
    // the drawer can only be open on a citation, which needs an accepted
    // artifact, and "prevents *fresh* acceptance" can only be said of a run
    // that has started and accepted nothing. So run 1 is driven to COMPLETE
    // for its citation, and run 2 is prepared and started with the journey
    // worker stopped -- RUNNING, its own snapshot pinned, its gates released,
    // unclaimed. Stopping the worker is not a convenience: the deterministic
    // provider finishes a three-node LITE route in seconds, so a withdrawal
    // fired after Start would be racing it, and a race is not evidence.
    withdrawalCase = await createCase(page, `Journey withdrawal ${randomUUID()}`);
    await admit(page, withdrawalCase, await journeyPack());
    const completed = await prepareRun(page, withdrawalCase);
    await page.locator("[data-work-controls] [data-action='START_RUN']").click();
    await expect(page.locator("[data-work-controls] [data-command-success]")).toContainText(
      "Run enqueued.",
    );
    // The worker has already exited once (decision 12) and holds no lease on
    // this run, so this is seconds rather than the 300 s of test 4.
    await waitForNode(page, withdrawalCase, completed, "CP-5", "COMPLETE", 180_000);

    withdrawalRun = await prepareRun(page, withdrawalCase);
    await stopJourneyWorker();
    await page.locator("[data-work-controls] [data-action='START_RUN']").click();
    await expect(page.locator("[data-work-controls] [data-command-success]")).toContainText(
      "Run enqueued.",
    );

    // The drawer, open on run 1's own citation of the PDF, and left open for
    // the rest of this test: everything below happens in a second tab, so
    // what the drawer does is what it does without being reloaded.
    await page.goto(`/analysis/?case=${withdrawalCase}&run=${completed}`);
    await page.locator("[data-handoff='CP-0'] [data-citation] [data-fact-chip]").first().click();
    const drawer = page.locator("[data-evidence-drawer]");
    await expect(drawer).toContainText(PDF_NAME);
    await expect(drawer.locator("[data-page-layer]")).toBeVisible();
    await expect(drawer.locator("[data-withdrawn]")).toHaveCount(0);

    // A second context rather than a second tab on this one: the edge's
    // session cookie is one name per context, and this journey's analyst
    // session on `page` must survive. Same persona, so this is one person
    // with two tabs open, which is the situation the claim is about.
    const other = await contextAs(browser, "analyst");
    try {
      await other.page.goto(`/upload/?case=${withdrawalCase}`);
      // The text report first, not the PDF the drawer is open on. Two
      // reasons: it is what makes run 2's pinned set incomplete without
      // taking the deterministic provider's own cited document away (the
      // journey worker refuses `ORCHESTRATION_SOURCE_NOT_PINNED` when the PDF
      // is not pinned, which would answer a different question), and it lets
      // the assertion below say that the drawer tracks *its own* source
      // rather than reacting to any withdrawal on the case.
      const text = other.page.locator("[data-source-pack] tbody tr", { hasText: TEXT_NAME });
      const control = text.locator("[data-action='WITHDRAW_SOURCE']");
      await expect(control).toBeVisible();
      // A live source offers its withdrawal: the control is available, not
      // refused. `RefusedControl` renders `data-refusal` only when it is.
      expect(await control.getAttribute("data-refusal")).toBeNull();
      // Registered before the press: the tail's refetch can land while the
      // assertions below run, and a waiter armed afterwards would wait for a
      // response that had already arrived.
      const refetched = page.waitForResponse(
        (response) =>
          new URL(response.url()).pathname === `/api/v1/cases/${withdrawalCase}/analysis` &&
          response.status() === 200,
        { timeout: 60_000 },
      );
      await control.click();
      await expect(text).toContainText("Withdrawn");
      // And nothing is left to withdraw on that row: the column is empty
      // rather than carrying a refusal the pack would have had to invent.
      await expect(
        text.locator("[data-withdraw-control] [data-action='WITHDRAW_SOURCE']"),
      ).toHaveCount(0);

      // `sources_changed` reaches the open tail on `page` and it refetches;
      // the drawer is unmoved, because the source it is open on is still
      // live. Waited for rather than assumed, so this is not vacuous.
      await refetched;
      await expect(drawer.locator("[data-withdrawn]")).toHaveCount(0);
      await expect(drawer.locator("[data-page-layer]")).toBeVisible();

      // Now the worker may have the run. It claims it, asks `execution_input`
      // for the pinned input, and is refused before any attempt, reservation
      // or provider call, so it parks the run STOPPED with that code.
      await startJourneyWorker();
      await expect
        .poll(
          async () => (await readRun(other.page, withdrawalCase, withdrawalRun))?.work?.stop_code,
          { timeout: 180_000, intervals: [2_000] },
        )
        .toBe("EVIDENCE_NOT_AVAILABLE");
      // No section renders `work.stop_code` -- it is on the wire and on no
      // surface -- so the line above reads the run document this browser
      // session is served, through the real edge. What the surface *does* say
      // is that nothing more can happen here: start and retry carry the same
      // code the command answers, and no node of this run was ever accepted.
      const parked = await readRun(other.page, withdrawalCase, withdrawalRun);
      expect(parked?.status).toBe("RUNNING");
      expect(parked?.nodes.map((node) => node.state)).not.toContain("COMPLETE");
      await other.page.goto(`/run/?case=${withdrawalCase}&run=${withdrawalRun}`);
      // `RETRY_RUN` is where the withdrawal is the only true refusal, so it is
      // asserted exactly. For `START_RUN` two rules hold at once -- the run is
      // already started and its sources are not live -- and which one the
      // surface shows is the order of `availability.py`'s queue, not a fact
      // about the withdrawal; asserting the exact code there would pin a list
      // order and go red on an unrelated reorder.
      await expect(
        other.page.locator("[data-work-controls] [data-action='RETRY_RUN']"),
      ).toHaveAttribute("data-refusal", "EVIDENCE_NOT_AVAILABLE");
      await expect(
        other.page.locator("[data-work-controls] [data-action='START_RUN']"),
      ).toHaveAttribute("data-refusal", /^(EVIDENCE_NOT_AVAILABLE|RUN_ALREADY_STARTED)$/);
      for (const moduleId of ROUTE_NODES) {
        await expect(nodeLocator(other.page, moduleId)).not.toHaveAttribute(
          "data-state",
          "COMPLETE",
        );
      }

      // And the source the drawer is open on, withdrawn last so the run above
      // was parked on evidence rather than on the journey worker's own
      // refusal to answer a pack it cannot see.
      await other.page.goto(`/upload/?case=${withdrawalCase}`);
      const pdf = other.page.locator("[data-source-pack] tbody tr", { hasText: PDF_NAME });
      await pdf.locator("[data-action='WITHDRAW_SOURCE']").click();
      await expect(pdf).toContainText("Withdrawn");
    } finally {
      await other.context.close();
      // The worker was stopped before this test's run was enqueued, and the
      // start above is inside the try. `compose start` on a running service is
      // a no-op, so starting it again here costs nothing and stops an
      // assertion failure anywhere in this test from leaving the shared
      // stack's worker down for every test after it -- the shape that turns
      // one failure into six and makes triage read as a cascade.
      await startJourneyWorker();
    }

    // The open drawer, never reloaded, now says its source is withdrawn and
    // reads no page. The citation stays: the conclusion resting on it has to
    // remain explicable.
    await expect(drawer.locator("[data-withdrawn]")).toBeVisible({ timeout: 60_000 });
    await expect(drawer.locator("[data-page-layer]")).toHaveCount(0);
    await expect(drawer.locator("blockquote.matched")).toContainText(QUOTE);
  });

  test("journey: standing is granted, and a revoked member's read is answered 404", async ({
    browser,
  }) => {
    // The two membership commands have no control anywhere in the workspace
    // and no entry in `ActionName` -- deliberately, because no section serves
    // an Admin panel to offer them from -- so they are driven here as
    // authenticated requests from the analyst's own browser session, through
    // the real edge. What that proves is the route, the edge's identity, the
    // ADMIN floor and what the grant and the revocation do to a reader's
    // reads; what it cannot prove is a control, because there is none.
    await receipt(
      await postAs(page, `/api/v1/cases/${caseId}/members`, {
        user_id: READER_USER_ID,
        standing: "READER",
      }),
      201,
    );

    const reader = await contextAs(browser, "reader");
    try {
      const read = await reader.page.request.get(`/api/v1/cases/${caseId}/analysis?run=${runId}`, {
        headers: { accept: "application/json" },
      });
      expect(read.status()).toBe(200);
      await reader.page.goto(`/analysis/?case=${caseId}&run=${runId}`);
      await expect(reader.page.locator("main#body [data-surface-state='unavailable']")).toHaveCount(
        0,
      );
      await expect(reader.page.getByText(QUOTE).first()).toBeVisible();

      await receipt(
        await postAs(page, `/api/v1/cases/${caseId}/members/${READER_USER_ID}/revocation`, {}),
        200,
      );

      // A revoked member is answered exactly as a stranger is (CLAUDE.md
      // "Auth edge": unknown and unauthorized both 404), and the section they
      // were looking at is unavailable on the next read -- with none of the
      // evidence it had shown them.
      const after = await reader.page.request.get(`/api/v1/cases/${caseId}/analysis?run=${runId}`, {
        headers: { accept: "application/json" },
      });
      expect(after.status()).toBe(404);
      await reader.page.reload();
      await expect(reader.page.locator("main#body [data-surface-state='unavailable']")).toHaveCount(
        1,
      );
      await expect(reader.page.getByText(QUOTE)).toHaveCount(0);
    } finally {
      await reader.context.close();
    }
  });

  test("journey: a revision is saved from the run's accepted artifacts and a draft narrative", async () => {
    // **The workspace has no path to the first save, and this is where that
    // shows.** `sectionUrl` answers null for report without `?revision`,
    // `read_report` refuses `DELIVERABLE_NOT_FOUND` without the row, and the
    // only thing in the workspace that ever sets `?revision` is
    // `FilingControls`' own post-save `setParams` -- which lives on the
    // section that cannot be reached. So Report is unavailable here,
    await page.goto(`/report/?case=${caseId}&run=${runId}`);
    await expect(page.locator("main#body [data-surface-state='unavailable']")).toHaveCount(1);
    // and the first revision is made as an authenticated request from this
    // same browser session, through the real edge, because there is no press
    // that would make it. Everything after this one call is pressed on the
    // surface.
    // The route's own node id, read from the run document rather than spelled
    // out here: a figure names a *route node*, not a module, and CP-0 on this
    // pathway is `RN-LITE_CREDIT_22-LITE_EARNINGS_UPDATE-01-CP-0`.
    const gate = (await readRun(page, caseId, runId))?.nodes.find(
      (node) => node.module_id === "CP-0",
    );
    if (!gate) throw new Error("the run document names no CP-0 node");
    const first = await postAs(page, `/api/v1/cases/${caseId}/runs/${runId}/revisions`, {
      expected_revision_id: null,
      narrative: [
        [{ text: "The covenant certificate is the register this opinion rests on.", figure: null }],
        // A figure span: the wire accepts one and the Report surface cannot
        // compose one, since a figure names a citation of a verified record
        // and that needs a picker the surface does not have. The host fills
        // the document, the page and the quote from the record itself.
        [{ text: null, figure: { route_node_id: gate.route_node_id, citation_index: 0 } }],
      ],
    });
    const firstRevision = (await receipt<{ revision_id: string }>(first, 201)).revision_id;

    await page.goto(`/report/?case=${caseId}&run=${runId}&revision=${firstRevision}`);
    const report = page.locator("[data-report-v1]");
    await expect(report).toHaveAttribute("data-revision", firstRevision);
    // Derived from the run's accepted artifacts, not from the request: all
    // three of the route's handoffs are in the payload.
    await expect(page.locator("[data-report-artifact]")).toHaveCount(3);
    // And the figure reads back as the host resolved it.
    const figure = page.locator("[data-report-paragraph='1']");
    await expect(figure).toContainText(gate.route_node_id);
    await expect(figure).toContainText(QUOTE);

    // A draft carrying an ASCII digit is refused, and the clearance a reader
    // is given names an act this surface offers no way to perform.
    await page.locator("#narrative-draft").fill(DIGIT_DRAFT);
    await page.locator("[data-filing-controls] [data-action='SAVE_REVISION']").click();
    const refused = page.locator(
      "[data-filing-controls] [role='alert'] [data-refusal='NARRATIVE_FIGURE_UNREFERENCED']",
    );
    await expect(refused).toBeVisible();
    await expect(refused).toContainText("validated reference");

    // The draft this surface can compose, saved by pressing Save. The
    // response is waited for rather than the success note asserted: a
    // successful save corrects the address, and a new `?revision` remounts
    // the section (`Workspace`'s `mountKey`), so the note is genuinely
    // transient and asserting it would be a race.
    await page.locator("#narrative-draft").fill(DRAFT);
    const [saved] = await Promise.all([
      page.waitForResponse(
        (response) =>
          response.request().method() === "POST" &&
          new URL(response.url()).pathname === `/api/v1/cases/${caseId}/runs/${runId}/revisions`,
      ),
      page.locator("[data-filing-controls] [data-action='SAVE_REVISION']").click(),
    ]);
    expect(saved.status()).toBe(201);
    revisionId = ((await saved.json()) as { revision_id: string }).revision_id;
    expect(revisionId).not.toBe(firstRevision);
    // The address is corrected, not navigated, and the document the section
    // then reads is the revision just saved.
    await expect.poll(() => new URL(page.url()).searchParams.get("revision")).toBe(revisionId);
    await expect(report).toHaveAttribute("data-revision", revisionId);
    await expect(page.locator("[data-report-narrative]")).toContainText(
      "The covenant certificate states headroom",
    );
    payloadSha256 = (await report.getAttribute("data-payload")) ?? "";
    expect(payloadSha256).toHaveLength(64);
  });

  test("journey: the opinion is signed on the bytes on screen, and a signer cannot freeze", async () => {
    const [signed] = await Promise.all([
      page.waitForResponse(
        (response) =>
          response.request().method() === "POST" &&
          new URL(response.url()).pathname ===
            `/api/v1/cases/${caseId}/revisions/${revisionId}/signature`,
      ),
      page.locator("[data-filing-controls] [data-action='SIGN_OPINION']").click(),
    ]);
    expect(signed.status()).toBe(200);
    // Signed on exactly the bytes this page was showing: the digest the
    // control sent is the one the section rendered, and the receipt names it.
    expect(((await signed.json()) as { payload_sha256: string }).payload_sha256).toBe(
      payloadSha256,
    );
    await expect(
      page.locator("[data-filing-controls] [data-command-success]", {
        hasText: "Sign opinion: done.",
      }),
    ).toBeVisible();

    // The three-actor rule. The surface stops offering Freeze to the person
    // who just signed, with the code the command would answer --
    const freeze = page.locator("[data-filing-controls] [data-action='FREEZE_DELIVERABLE']");
    await expect(freeze).toHaveAttribute("data-refusal", "APPROVER_NOT_INDEPENDENT", {
      timeout: 30_000,
    });
    // -- and the rule is the store's, not the surface's: the same request the
    // control would have made, made anyway from this session, is refused at
    // commit under the case lock. Persona is not authority.
    const forced = await postAs(page, `/api/v1/cases/${caseId}/revisions/${revisionId}/freeze`, {
      payload_sha256: payloadSha256,
    });
    expect(forced.status()).toBe(400);
    expect(((await forced.json()) as { code: string }).code).toBe("APPROVER_NOT_INDEPENDENT");
  });

  test("journey: a second approver freezes, the Committee reads the act back, and a freezer cannot file", async ({
    browser,
  }) => {
    // Both remaining approvers are given standing before either navigates:
    // without it the Report section is not readable by them at all.
    for (const member of [APPROVER_USER_ID, FILER_USER_ID]) {
      await receipt(
        await postAs(page, `/api/v1/cases/${caseId}/members`, {
          user_id: member,
          standing: "APPROVER",
        }),
        201,
      );
    }

    const approver = await contextAs(browser, "approver");
    try {
      await approver.page.goto(`/report/?case=${caseId}&run=${runId}&revision=${revisionId}`);
      const freeze = approver.page.locator(
        "[data-filing-controls] [data-action='FREEZE_DELIVERABLE']",
      );
      // Offered to this actor, refused to the signer: the same document, read
      // by two different people.
      expect(await freeze.getAttribute("data-refusal")).toBeNull();
      const [frozen] = await Promise.all([
        approver.page.waitForResponse(
          (response) =>
            response.request().method() === "POST" &&
            new URL(response.url()).pathname ===
              `/api/v1/cases/${caseId}/revisions/${revisionId}/freeze`,
        ),
        freeze.click(),
      ]);
      expect(frozen.status()).toBe(200);

      // The Committee section, which refuses a revision that is not frozen,
      // now serves this one and names the two actors behind it. This is the
      // read-back the plan asks for: an act made through a control, proved by
      // a section that rebuilds the audit event from its own receipt.
      await approver.page.goto(`/committee/?case=${caseId}&run=${runId}&revision=${revisionId}`);
      const filing = approver.page.locator("[data-committee-filing]");
      await expect(filing).toHaveAttribute("data-state", "frozen");
      await expect(filing).toContainText(ANALYST_USER_ID);
      await expect(filing).toContainText(APPROVER_USER_ID);

      // A freezer cannot file, on the surface and at commit.
      await approver.page.goto(`/report/?case=${caseId}&run=${runId}&revision=${revisionId}`);
      await expect(
        approver.page.locator("[data-filing-controls] [data-action='FILE_DELIVERABLE']"),
      ).toHaveAttribute("data-refusal", "APPROVER_NOT_INDEPENDENT");
      const forced = await postAs(
        approver.page,
        `/api/v1/cases/${caseId}/revisions/${revisionId}/filing`,
        { payload_sha256: payloadSha256 },
      );
      expect(forced.status()).toBe(400);
      expect(((await forced.json()) as { code: string }).code).toBe("APPROVER_NOT_INDEPENDENT");
    } finally {
      await approver.context.close();
    }
  });

  test("journey: a third approver files, and the Committee serves the receipt", async ({
    browser,
  }) => {
    const filer = await contextAs(browser, "filer");
    try {
      await filer.page.goto(`/report/?case=${caseId}&run=${runId}&revision=${revisionId}`);
      const file = filer.page.locator("[data-filing-controls] [data-action='FILE_DELIVERABLE']");
      expect(await file.getAttribute("data-refusal")).toBeNull();
      const [filed] = await Promise.all([
        filer.page.waitForResponse(
          (response) =>
            response.request().method() === "POST" &&
            new URL(response.url()).pathname ===
              `/api/v1/cases/${caseId}/revisions/${revisionId}/filing`,
        ),
        file.click(),
      ]);
      expect(filed.status()).toBe(200);

      await filer.page.goto(`/committee/?case=${caseId}&run=${runId}&revision=${revisionId}`);
      const filing = filer.page.locator("[data-committee-filing]");
      await expect(filing).toHaveAttribute("data-state", "filed");
      await expect(filing).toContainText(FILER_USER_ID);
      // The detached receipt the filing command persists after its audit
      // event, served by the section: the three actors, the payload and the
      // event it names.
      const receipt = filer.page.locator("[data-committee-receipt]");
      await expect(receipt).toBeVisible();
      await expect(receipt).toContainText(ANALYST_USER_ID);
      await expect(receipt).toContainText(APPROVER_USER_ID);
      await expect(receipt).toContainText(FILER_USER_ID);
      await expect(receipt).toContainText(payloadSha256);
      // Filing once: the act is no longer offered to anyone.
      await filer.page.goto(`/report/?case=${caseId}&run=${runId}&revision=${revisionId}`);
      await expect(
        filer.page.locator("[data-filing-controls] [data-action='FILE_DELIVERABLE']"),
      ).toHaveAttribute("data-refusal", "DELIVERABLE_ALREADY_FILED");
    } finally {
      await filer.context.close();
    }
  });

  test("journey: the Book names every credit of the portfolio on one stated basis", async () => {
    // What the Book can be driven to on this stack, and what it cannot.
    // `read_book` fills a credit's cells from the accepted CP-CF projection,
    // and no run made through the API can carry CP-CF on any pathway:
    // `create_run` resolves the route with no `RouteExtensions`
    // (`server/api/commands/runs.py`) and `CreateRun` carries no field to ask
    // for one, while CP-CF is a host extension appended only by
    // `resolve_route(..., extensions=RouteExtensions(model_extension=True))`,
    // whose one caller is the qualification harness. Not a property of the
    // LITE route: `ADAPTER_ROUTES` enables three pathways and
    // `FULL_CREDIT_32/RELATIVE_VALUE` carries every one of CP-CF's
    // `MODEL_OWNERS`, so it would append CP-CF if anything asked. So every
    // credit here is
    // `NO_ACCEPTED_FORECAST`, no period is served, no comparison table is
    // drawn and no cell exists to open a passport from. The ten-field
    // passport is therefore not reachable through the production stack at
    // all, and this test proves the reachable part rather than asserting an
    // unreachable step as passing: the credits the analyst holds, side by
    // side, on one basis the page states, each saying in the document's own
    // typed words why it carries no figure.
    await page.goto("/book/");
    await expect(page.locator("[data-book-v1]")).toBeVisible();
    await expect(page.locator("[data-basis-period]")).toHaveText("EVERY_ACCEPTED_PERIOD");
    const credits = page.locator("[data-book-credits] li");
    // The three cases this journey made, all of them the analyst's own, which
    // is two to four credits side by side (`BOOK_CASES_MAX`).
    await expect(credits).toHaveCount(3);
    for (const credit of [caseId, withdrawalCase]) {
      const row = page.locator(`[data-book-credits] li[data-case='${credit}']`);
      await expect(row).toBeVisible();
      await expect(row).toContainText("NO_ACCEPTED_FORECAST");
    }
    // No table and no cell -- said as an absence rather than left unasserted,
    // so the day CP-CF runs here this test fails and is rewritten to open the
    // passport instead of recording that it cannot. Both markers appear the
    // day a cell exists: `table.tbl` is the comparison table, drawn only for a
    // non-empty `periodsOf(rows)`, and `[data-cell]` is `MetricCell`'s own.
    // A `getByRole("dialog")` count stood here too and is removed: the only
    // dialog on this page is `MetricPassport`, which nothing opens without a
    // click on a cell, and this test clicks nothing -- so it read green in the
    // reachable state as well as this one, and could not be the tripwire the
    // sentence above claims.
    await expect(page.locator("table.tbl")).toHaveCount(0);
    await expect(page.locator("[data-cell]")).toHaveCount(0);
  });
});
