// The real-stack journey (Task 4.5, slice 4.5e2): one persona, one case, one
// LITE run, driven through the real edge and the real API -- no fixture, no
// demo mode. `tests/journey/run.py` brings up `compose.smoke.yaml`'s
// disposable stack with the deterministic journey worker and starts the test
// edge (`tests/journey/edge.py`) on this config's `baseURL` before this file
// ever runs, and tears both down afterwards; this file only ever talks to
// that edge, the way a browser in production only ever talks to the
// operator's edge.
//
// Serial and shared: every test after the first two builds on the case, run,
// route and gate state the earlier ones left behind, on one `Page` created in
// `beforeAll` rather than the per-test default -- the same pattern
// `tests/journey/run.py`'s own state (the edge's login session, the stack's
// containers) already uses, because this journey *is* one continuous session.
import { execFile } from "node:child_process";
import { randomUUID } from "node:crypto";
import http from "node:http";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { expect, test, type Page } from "@playwright/test";

const execFileAsync = promisify(execFile);

const REPO_ROOT = path.resolve(fileURLToPath(new URL(".", import.meta.url)), "..", "..", "..");
const COMPOSE_FILE = path.join(REPO_ROOT, "compose.smoke.yaml");
const PROJECT = "caos-workbench-smoke";
const PYTHON = path.join(REPO_ROOT, ".venv", "bin", "python");

const ANALYST_USER_ID = "6a0e1c2d-0000-4000-8000-00000000a001";
const QUOTE = "Total debt at 31 December 2026";
const ISSUER_ID = "JOURNEY-HOLDINGS";
const ISSUER_NAME = "Journey Holdings";
const REPORTING_PERIOD = "FY2026 Q2";
const ANALYSIS_DATE = "2026-09-14";
const ROUTE_NODES = ["CP-0", "CP-L10", "CP-5"] as const;
const EDGE_ORIGIN = "http://127.0.0.1:18080";

interface PackFile {
  name: string;
  mimeType: string;
  buffer: Buffer;
}

/** The exact bytes `journey.worker.completions_for` will hash and expect
    among the run's pinned live sources -- generated by calling the same
    `journey.pack.journey_pack()` the worker calls, never re-implemented here
    byte for byte, so admission and the worker's citation always agree. */
async function journeyPack(): Promise<PackFile[]> {
  const { stdout } = await execFileAsync(
    PYTHON,
    [
      "-c",
      "import base64, json\n" +
        "from journey.pack import journey_pack\n" +
        "print(json.dumps([[n, base64.b64encode(b).decode()] for n, b in journey_pack()]))\n",
    ],
    {
      cwd: REPO_ROOT,
      env: {
        ...process.env,
        PYTHONPATH: `${path.join(REPO_ROOT, "tests")}${path.delimiter}${REPO_ROOT}`,
      },
    },
  );
  const rows: [string, string][] = JSON.parse(stdout);
  return rows.map(([name, b64]) => ({
    name,
    mimeType: name.endsWith(".pdf") ? "application/pdf" : "text/plain",
    buffer: Buffer.from(b64, "base64"),
  }));
}

/** Restarts one `compose.smoke.yaml` service in place, using the same
    project and compose file `tests/journey/run.py` brought the stack up
    with; the environment it needs (`CAOS_EDGE_TOKEN`, `JOURNEY_STATE_DIR`,
    …) is already this process's own, inherited from that same script. */
async function restartService(service: string): Promise<void> {
  await execFileAsync(
    "docker",
    ["compose", "-p", PROJECT, "-f", COMPOSE_FILE, "--profile", "journey", "restart", service],
    { cwd: REPO_ROOT },
  );
}

/** `JOURNEY_EXIT_AFTER_FIRST_ACCEPT` (Task 4.5 decision 12) has already made
    the worker exit(137) once, and nothing in `compose.smoke.yaml` restarts
    it on its own. */
function restartJourneyWorker(): Promise<void> {
  return restartService("journey-worker");
}

async function loginAs(page: Page, persona: "analyst" | "intruder"): Promise<void> {
  const response = await page.request.get(`/_edge/login?persona=${persona}`);
  expect(response.status()).toBe(200);
}

function nodeLocator(page: Page, moduleId: string) {
  return page.locator(`button.node[data-node='${moduleId}']`);
}

/** Polls for a node's state over the run API directly, not by trusting the
    open SSE tail to repaint the DOM and not by reloading the page every
    cycle: the real stream stays connected (confirmed against the network
    trace) while the run genuinely progresses server-side, but a live-push
    repaint is not something this journey depends on to prove the run
    finished. An earlier version reloaded the whole page every 2s, which
    opens a fresh `/events` SSE connection per reload -- the API's SSE tail
    holds a connection until `TAIL_DEADLINE` (300s) even after the client has
    navigated away, with nothing checking for an earlier disconnect, so over
    a 320s wait that piled up abandoned connections past the API's own
    `--limit-concurrency 32` (Dockerfile) and answered later requests, in this
    test and the next one, with a bare 503. Polling the JSON directly opens
    and closes one short-lived request per cycle instead, then reloads once
    at the end to sync the DOM for the assertions that follow. */
async function waitForNode(
  page: Page,
  caseId: string,
  runId: string,
  moduleId: string,
  state: string,
  timeoutMs: number,
): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  let current: string | undefined;
  for (;;) {
    try {
      const response = await page.request.get(`/api/v1/cases/${caseId}/run?run=${runId}`, {
        timeout: 10_000,
      });
      if (response.ok()) {
        const body = (await response.json()) as {
          body: { run: { nodes: { module_id: string; state: string }[] } | null };
        };
        current = body.body.run?.nodes.find((n) => n.module_id === moduleId)?.state;
        if (current === state) break;
      }
    } catch {
      // A slow, refused or unparsable read counts as "not yet", never as a hang.
    }
    if (Date.now() >= deadline) {
      throw new Error(
        `${moduleId} did not reach ${state} within ${timeoutMs}ms (last: ${current})`,
      );
    }
    await page.waitForTimeout(2_000);
  }
  // Sync the visible DOM once the API confirms the state, retrying the
  // reload itself since a request right after a long wait can still meet a
  // transient 503 while other abandoned connections from this same wait
  // drain.
  await expect(async () => {
    await page.reload({ timeout: 10_000 });
    await expect(nodeLocator(page, moduleId)).toHaveAttribute("data-state", state, {
      timeout: 10_000,
    });
  }).toPass({ timeout: 30_000 });
}

/** A tiny HTTP server on its own ephemeral port -- a different origin from
    the edge on any browser's same-site rules -- serving one page that fires
    a cross-site, no-preflight ("simple request") POST at `target` the moment
    it loads. `text/plain` is CORS-safelisted, so the browser sends it with
    no permission check; whether it *changes* anything is exactly what
    decision 5's Origin / `Sec-Fetch-Site` check and `SameSite=Lax` on the
    edge's cookie are there to refuse. */
async function serveCrossSitePost(
  targetUrl: string,
  body: string,
): Promise<{ url: string; close: () => Promise<void> }> {
  const html =
    "<!doctype html><body><script>" +
    `fetch(${JSON.stringify(targetUrl)}, { method: "POST", mode: "no-cors", credentials: "include",` +
    ` headers: { "Content-Type": "text/plain" }, body: ${JSON.stringify(body)} })` +
    ".finally(() => { document.title = 'sent'; });" +
    "</script></body>";
  const server = http.createServer((_req, res) => {
    res.writeHead(200, { "content-type": "text/html" });
    res.end(html);
  });
  await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
  const address = server.address();
  if (address === null || typeof address === "string") throw new Error("no ephemeral port");
  return {
    url: `http://127.0.0.1:${address.port}/`,
    close: () => new Promise<void>((resolve) => server.close(() => resolve())),
  };
}

test.describe.serial("journey", () => {
  let page: Page;
  let caseId = "";
  let runId = "";

  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
    await loginAs(page, "analyst");
    // Fails in seconds, not the full test timeout, when the edge or the API
    // is misconfigured (a stale edge token, a port collision with a leftover
    // process, …): the very first navigation must not read back a refusal
    // body instead of the workspace.
    await page.goto("/directory/");
    await expect(page.getByText("EDGE_NOT_TRUSTED")).toHaveCount(0, { timeout: 15_000 });
    await expect(page.locator("[data-new-case]")).toBeVisible({ timeout: 15_000 });
  });

  test.afterAll(async () => {
    await page.close();
  });

  test("journey: create a case and admit a mixed text and PDF pack", async () => {
    const title = `Journey ${randomUUID()}`;
    await page.goto("/directory/");
    await page.getByLabel("New case title").fill(title);
    await page.locator("[data-new-case] [aria-label='Create case']").click();
    const success = page.locator("[data-new-case-success]");
    await expect(success).toBeVisible();
    const text = (await success.textContent()) ?? "";
    const found = text.match(/Case ([0-9a-f-]{36}) created\./);
    if (!found) throw new Error(`case id not found in: ${text}`);
    caseId = found[1] ?? "";
    expect(caseId).not.toBe("");
    await expect(page.locator(`[data-case='${caseId}']`)).toContainText(title);

    await page.goto(`/upload/?case=${caseId}`);
    const pack = await journeyPack();
    await page
      .locator("[data-admit-sources] input[type=file]")
      .setInputFiles(
        pack.map((file) => ({ name: file.name, mimeType: file.mimeType, buffer: file.buffer })),
      );
    await page.locator("[data-admit-sources] [aria-label='Admit sources']").click();
    await expect(page.locator("[data-admit-sources-success]")).toContainText(
      "2 source(s) admitted.",
    );
    await expect(page.locator("[data-source-pack] tbody tr")).toHaveCount(2);
  });

  test("journey: select the LITE route and pin the subject", async () => {
    await page.goto(`/run/?case=${caseId}`);
    await expect(page.locator("[data-route-select] option")).toHaveCount(2);
    await expect(
      page.locator("[data-route-select] option", {
        hasText: "LITE_CREDIT_22 · LITE_EARNINGS_UPDATE",
      }),
    ).toHaveCount(1);
    await page.locator("[data-route-select]").selectOption({
      label: "LITE_CREDIT_22 · LITE_EARNINGS_UPDATE",
    });
    // Creation is not idempotent: retrying the click can create a second run
    // while the worker claims the first, splitting this shared journey's
    // observed run from its executed run. A transient command failure must
    // fail this fresh-stack journey rather than silently changing its subject.
    await page.locator("[data-create-run] [data-action='CREATE_RUN']").click();
    await expect(page.locator("[data-create-run] [data-command-success]")).toContainText(
      "Run created.",
      { timeout: 15_000 },
    );
    await expect(page.locator("[data-run]")).toBeVisible({ timeout: 15_000 });
    runId = (await page.locator("[data-run]").getAttribute("data-run")) ?? "";
    expect(runId).not.toBe("");

    await page.locator("[data-pin-input] input[data-field='issuer_id']").fill(ISSUER_ID);
    await page.locator("[data-pin-input] input[data-field='issuer_name']").fill(ISSUER_NAME);
    await page
      .locator("[data-pin-input] input[data-field='reporting_period']")
      .fill(REPORTING_PERIOD);
    await page.locator("[data-pin-input] input[data-field='analysis_date']").fill(ANALYSIS_DATE);
    await page.locator("[data-pin-input] [data-action='PIN_RUN_INPUT']").click();
    await expect(page.locator("[data-pin-input] [data-command-success]")).toContainText(
      "Subject pinned.",
    );
  });

  test("journey: preview and approve the source-set and research-plan gates", async () => {
    for (const gate of ["SOURCE_SET", "RESEARCH_PLAN"] as const) {
      const panel = page.locator(`[data-gate-panel='${gate}']`);
      await expect(panel).toBeVisible();
      await panel.locator(`[data-preview-gate='${gate}']`).click();
      await expect(panel.locator("[data-gate-preview-content]")).not.toBeEmpty();
      const approve = panel.locator(
        `[data-action='APPROVE_SOURCE_SET'], [data-action='APPROVE_RESEARCH_PLAN']`,
      );
      await approve.click();
      await expect(panel).toContainText("RELEASED", { timeout: 15_000 });
    }
    const pinned = await page.evaluate(
      () => document.querySelector("[data-work-controls]") !== null,
    );
    expect(pinned).toBe(true);
  });

  test("journey: start the run and the worker completes it after one kill and restart", async () => {
    await page.locator("[data-work-controls] [data-action='START_RUN']").click();
    await expect(page.locator("[data-work-controls] [data-command-success]")).toContainText(
      "Run enqueued.",
    );

    if (process.env.JOURNEY_FAST === "1") {
      // Local iteration only, never the real gate: `run.py` always forces
      // `JOURNEY_EXIT_AFTER_FIRST_ACCEPT=1`, so reaching this branch means a
      // developer ran the stack by hand with that unset -- the worker never
      // exits, so every node completes without the real kill or the 300 s
      // lease wait below. The final chromium run and the final three-engine
      // run must never set `JOURNEY_FAST`.
      await waitForNode(page, caseId, runId, "CP-0", "COMPLETE", 60_000);
      await waitForNode(page, caseId, runId, "CP-L10", "COMPLETE", 60_000);
      await waitForNode(page, caseId, runId, "CP-5", "COMPLETE", 60_000);
    } else {
      // The journey worker exits(137) right after its first acceptance
      // (decision 12); the frontier's first node is CP-0, so its acceptance
      // is what the exit waits for.
      await waitForNode(page, caseId, runId, "CP-0", "COMPLETE", 120_000);
      await restartJourneyWorker();
      // The crashed process's work lease (`server/store/work.py`'s
      // `LEASE_SECONDS = 300`) is not released early -- CLAUDE.md's Phase 2
      // ledger entry "A stale lease holder can still pay once" is exactly
      // this: nothing reclaims a lease before it naturally expires, so the
      // restarted container (a new process, a new worker identity) cannot
      // claim CP-L10 until the original lease's 300 s run out. This wait is
      // that real architectural pause, not a margin for slowness.
      await waitForNode(page, caseId, runId, "CP-L10", "COMPLETE", 320_000);
      await waitForNode(page, caseId, runId, "CP-5", "COMPLETE", 60_000);
    }
    await expect(page.locator("dt:text-is('Status') + dd")).toContainText("COMPLETE", {
      timeout: 30_000,
    });
  });

  test("a stale view holds its figures until Reload", async () => {
    // A second run, created but never pinned or started, becomes the case's
    // latest -- the SSE tail still open on this page refetches on every
    // event this creates, and the figures shown stay run 1's regardless,
    // because they are bound to the `run` query this page was opened with,
    // not to whichever run is now latest. Only navigating to a different
    // `run` -- the one act "Reload" stands for here -- would show run 2's.
    const before = await page.locator("[data-run]").getAttribute("data-run");
    await page.locator("[data-create-run] [data-action='CREATE_RUN']").click();
    await expect(page.locator("[data-create-run] [data-command-success]")).toContainText(
      "Run created.",
    );
    // The API's own `--limit-concurrency 32` (Dockerfile) can answer a
    // request with a bare 503 "Service Unavailable" while the reload-driven
    // polling above (test 4's 300 s lease wait) still has connections
    // draining -- a transient real-server condition, not this page's fault,
    // so retry the navigation the same way `waitForNode` tolerates a slow
    // repaint.
    await expect(async () => {
      await page.goto(`/run/?case=${caseId}&run=${runId}`);
      await expect(page.locator("[data-stale-run]")).toBeVisible({ timeout: 5_000 });
    }).toPass({ timeout: 30_000 });
    await expect(page.locator("[data-run]")).toHaveAttribute("data-run", before ?? runId);
    const row = page.locator(`[data-run-row='${runId}']`);
    await expect(row).toHaveAttribute("data-displayed", "true");
    await expect(row).toHaveAttribute("data-latest", "false");
  });

  test("journey: analysis shows labelled source facts, model analysis and limitations", async () => {
    await page.goto(`/analysis/?case=${caseId}&run=${runId}`);
    await expect(page.locator("[data-handoff]")).toHaveCount(3);
    for (const moduleId of ROUTE_NODES) {
      const card = page.locator(`[data-handoff='${moduleId}']`);
      await expect(card).toBeVisible();
      await expect(card.locator("[data-qa-status]")).toContainText("Passed");
      await expect(card.locator("[data-committee-status]")).not.toBeEmpty();
      await expect(card.locator("[data-limitation-flags]")).toBeVisible();
      await expect(card.locator("[data-model-analysis] .model-text")).not.toBeEmpty();
      const facts = card.locator("[data-citation]");
      await expect(facts.first()).toBeVisible();
      await expect(facts.first().locator("blockquote.matched")).toContainText(QUOTE);
    }
  });

  test("the highlight covers the rendered words of the matched text", async () => {
    const card = page.locator("[data-handoff='CP-0']");
    await card.locator("[data-citation] [data-fact-chip]").first().click();
    const drawer = page.locator("[data-evidence-drawer]");
    await expect(drawer).toContainText("Text layer from the token index");
    const line = drawer.locator("[data-page-line]", { hasText: QUOTE });
    const highlight = drawer.locator("[data-highlight]");
    await expect(line).toBeVisible();
    await expect(highlight).toHaveCount(1);
    await expect
      .poll(async () => {
        const words = await line.boundingBox();
        const box = await highlight.boundingBox();
        if (!words || !box) return false;
        // Unlike the workbench's demo fixture (whose quote is a whole line),
        // QUOTE here is only the line's leading words -- "Total debt at 31
        // December 2026" out of "…2026 stood at 1,240 million" -- so the
        // highlight is correctly narrower than the line, not equal to it.
        // What must hold is the shared origin and line height (the same
        // stored rectangle placed the highlight this test opened), and a
        // width that covers a real word span: narrower than the whole line,
        // wider than a sliver.
        return (
          Math.abs(box.x - words.x) <= 4 &&
          Math.abs(box.y - words.y) <= 4 &&
          Math.abs(box.height - words.height) <= 4 &&
          box.width > words.width * 0.3 &&
          box.width < words.width
        );
      })
      .toBe(true);
  });

  test("Escape returns focus to the chip that opened the drawer", async () => {
    const chip = page.locator("[data-handoff='CP-0'] [data-citation] [data-fact-chip]").first();
    await expect(page.getByRole("dialog")).toBeVisible();
    await page.keyboard.press("Escape");
    await expect(page.getByRole("dialog")).toHaveCount(0);
    await expect(chip).toBeFocused();
  });

  test("a dropped stream resumes after its Last-Event-ID", async () => {
    // The tail this page's Analysis view opened is real and open, but by now
    // (several navigations past the run's own completion) it has gone idle:
    // nothing has happened on this case since, so its `EventSource` has no
    // `id:` yet to remember. Admitting one more harmless source (the same
    // pack file again -- content-addressed, so this is a no-op on the store
    // beyond one more row) emits `sources_changed`, which reaches this exact
    // tab's own long-open connection without any navigation of this page to
    // break it -- unlike creating another run, which this test does not need
    // and which would only add another stale-run case already covered above.
    const [firstFile] = await journeyPack();
    if (!firstFile) throw new Error("journey pack is empty");
    const admit = () =>
      page.request.post(`/api/v1/cases/${caseId}/sources`, {
        multipart: {
          document: {
            name: firstFile.name,
            mimeType: firstFile.mimeType,
            buffer: firstFile.buffer,
          },
        },
        // What the page's own fetch carries: the edge guard refuses an
        // unsafe method without a same-origin Origin (decision 5).
        headers: {
          "Idempotency-Key": randomUUID(),
          Origin: EDGE_ORIGIN,
          "Sec-Fetch-Site": "same-origin",
        },
      });
    // The first admission's refetch can move the view onto `?run=`, which
    // reopens its tail at the heads -- a fresh connection that has seen no
    // `id:` yet (Firefox does this; Chromium's timing hides it). The second
    // admission lands on the settled tail, so the connection the restart
    // severs has an id to send back. The server polls every 0.5 s
    // (POLL_INTERVAL); the waits cover that plus the refetch.
    expect((await admit()).status()).toBe(201);
    await page.waitForTimeout(2_000);
    expect((await admit()).status()).toBe(201);
    await page.waitForTimeout(2_000);

    // `EventSource` sends Last-Event-ID only on its own reconnect after the
    // server actually closes the connection -- toggling the browser
    // context's own network state does not touch an already-open socket, so
    // this drops the connection from the server side instead: restarting
    // `api` severs every open connection (including the test edge's proxied
    // one to it), and the browser's automatic reconnect, having consumed the
    // `id:`-bearing event above, sends it back as Last-Event-ID -- real
    // behaviour, not a fixture emulating it.
    const seenLastEventId = page.waitForRequest(
      async (request) =>
        request.url().includes(`/api/v1/cases/${caseId}/events`) &&
        Boolean((await request.allHeaders())["last-event-id"]),
      { timeout: 60_000 },
    );
    await restartService("api");
    await seenLastEventId;
  });

  test("journey: every section deep link loads through the edge with its query", async () => {
    const links: [string, string][] = [
      ["Case register", `/directory/`],
      ["Source pack", `/upload/?case=${caseId}`],
      ["Resolved route", `/run/?case=${caseId}&run=${runId}`],
      ["Handoffs", `/analysis/?case=${caseId}&run=${runId}`],
    ];
    for (const [marker, url] of links) {
      await page.goto(url);
      await expect(page.locator("main#body [data-surface-state='unavailable']")).toHaveCount(0);
      await expect(page.getByText(marker).first()).toBeVisible();
    }
  });

  test("journey: forged identity headers through the edge reach nobody else's case", async ({
    browser,
  }) => {
    // A separate browser context, not just a new tab on `page`'s -- the
    // edge's session cookie is one name per context, and logging in as
    // "intruder" here must never clobber the analyst session every other
    // test in this file depends on.
    const intruderContext = await browser.newContext({ baseURL: EDGE_ORIGIN });
    const intruder = await intruderContext.newPage();
    await loginAs(intruder, "intruder");
    const response = await intruder.request.get(`/api/v1/cases/${caseId}/analysis?run=${runId}`, {
      headers: { "x-caos-user": ANALYST_USER_ID, accept: "application/json" },
    });
    // The edge's own forwarded identity (the intruder's session, decision 2)
    // is what reaches the API; the client's `x-caos-user` is never in the
    // edge's allow-listed pass-through set and never arrives. An actor with
    // no standing on this case is answered exactly as an unknown one would be
    // (CLAUDE.md "Auth edge": unknown and unauthorized both 404).
    expect(response.status()).toBe(404);
    await intruder.goto(`/analysis/?case=${caseId}&run=${runId}`);
    await expect(intruder.locator("main#body [data-surface-state='unavailable']")).toHaveCount(1);
    await expect(intruder.getByText(QUOTE)).toHaveCount(0);
    await intruderContext.close();
  });

  test("journey: a cross-site form post through the edge changes nothing", async ({ browser }) => {
    const sentinel = `csrf-sentinel-${randomUUID()}`;
    const body = JSON.stringify({ title: sentinel });
    const foreign = await serveCrossSitePost(`${EDGE_ORIGIN}/api/v1/cases`, body);
    // `page`'s own context came from `browser.newPage()` in `beforeAll`,
    // which Playwright limits to that one page -- a second tab needs its
    // own context, the same way the intruder persona above does. It carries
    // no cookie, so the "no session" 401 the edge answers with is exactly
    // the point: this attacker page never had the analyst's session either.
    const attackerContext = await browser.newContext();
    try {
      const attacker = await attackerContext.newPage();
      await attacker.goto(foreign.url);
      await expect.poll(() => attacker.title()).toBe("sent");
      await attacker.close();
    } finally {
      await attackerContext.close();
      await foreign.close();
    }
    await page.goto("/directory/");
    await expect(page.locator("table.reg")).not.toContainText(sentinel);
  });

  test("the served policy refuses an injected inline script and the journey records no violation", async () => {
    await page.goto(`/analysis/?case=${caseId}&run=${runId}`);
    await page.evaluate(() => {
      (window as unknown as { __cspViolations: number }).__cspViolations = 0;
      window.addEventListener("securitypolicyviolation", () => {
        (window as unknown as { __cspViolations: number }).__cspViolations += 1;
      });
    });
    await page.evaluate(() => {
      // The served policy's `require-trusted-types-for 'script'; trusted-types
      // 'none'` (decision 5) refuses even the *assignment* here -- Trusted
      // Types guards `HTMLScriptElement.textContent` as a sink, and with no
      // policy named nothing can produce the `TrustedScript` it now demands,
      // so this throws before the element is ever appended. That is a
      // stronger refusal than a script-src violation on an appended element
      // would be, and the point this test proves either way: catch it so the
      // throw itself doesn't fail the read, and let the assertions below
      // confirm the script never ran and the browser still recorded a
      // violation.
      try {
        const script = document.createElement("script");
        script.textContent = "window.__journeyInlineScriptRan = true;";
        document.body.appendChild(script);
      } catch {
        // Refused at assignment, before script-src is ever asked.
      }
    });
    const ran = await page.evaluate(
      () => (window as unknown as { __journeyInlineScriptRan?: boolean }).__journeyInlineScriptRan,
    );
    expect(ran).toBeUndefined();
    const violations = await page.evaluate(
      () => (window as unknown as { __cspViolations: number }).__cspViolations,
    );
    expect(violations).toBeGreaterThan(0);
    // The refused script left no visible trace on the workspace itself: CSP
    // is the browser's own enforcement, and nothing here logs or renders it.
    await expect(page.locator("[data-command-error], [role='alert']")).toHaveCount(0);
  });
});
