"""The Phase 2 debt Phase 6 owes: a real PDF, a real extractor, real coordinates.

`docs/REBUILD_PLAN.md` lists `test_citations_anchor_in_an_extracted_pdf` under
Phase 6, owed by Phase 2. Phase 2 built the token index and the anchoring against
a plain-text extractor whose rectangles are derived from a declared fixed pitch --
honest for a `.txt` file, and a fiction for a page. This closes it with
coordinates that came out of the document.

The fixture is a PDF this file builds byte by byte rather than a binary checked
into the tree. It is a real PDF -- `pdfminer` parses it through the same path as
any other -- and unlike a blob, a reviewer can see what it says and where.
"""

from __future__ import annotations

from pathlib import Path
from uuid import UUID

import pytest

from server.blobs import BlobStore
from server.boundary_text import BoundaryText
from server.evidence.citations import anchor_citation
from server.evidence.extract import Extractor, Token
from server.evidence.ingest import Document, admit_pack
from server.evidence.pdf import PdfExtractor
from server.refusals import Refusal, RefusalCode
from server.store import StoreConnection

FIRST_LINE = "Total debt at 31 December 2026 was USD 1,240.0m"
SECOND_LINE = "Cash and equivalents stood at USD 310.5m"
# Where the fixture draws them: 12pt text at x=72, sixteen points apart.
LEFT_MARGIN = 72.0
LINE_GAP = 16.0


def raw_pdf(content: bytes, *, trailer: bytes = b"") -> bytes:
    """A one-page PDF whose content stream is exactly `content`.

    Written out rather than generated by a library, so the fixture has no
    dependency of its own and its contents are legible in the diff. `trailer`
    is spliced into the trailer dictionary -- an `/Encrypt` entry is how a
    fixture becomes an encrypted document. Every other builder in this file is
    a content-stream shorthand over this one, so a reviewer sees the same PDF
    object machinery once.
    """
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        b"/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
        b"<< /Length "
        + str(len(content)).encode()
        + b" >>\nstream\n"
        + content
        + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]
    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for number, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += str(number).encode() + b" 0 obj\n" + body + b"\nendobj\n"
    start_xref = len(out)
    out += b"xref\n0 " + str(len(objects) + 1).encode() + b"\n0000000000 65535 f \n"
    for offset in offsets:
        out += f"{offset:010d} 00000 n \n".encode()
    out += (
        b"trailer\n<< /Size "
        + str(len(objects) + 1).encode()
        + b" /Root 1 0 R "
        + trailer
        + b">>\nstartxref\n"
        + str(start_xref).encode()
        + b"\n%%EOF\n"
    )
    return bytes(out)


def minimal_pdf(lines: list[str], *, trailer: bytes = b"") -> bytes:
    """A one-page PDF drawing each line at a known position, one `Tj` each."""
    text = "BT\n/F1 12 Tf\n"
    y = 700
    for line in lines:
        text += f"1 0 0 1 {LEFT_MARGIN:.0f} {y} Tm\n({line}) Tj\n"
        y -= int(LINE_GAP)
    text += "ET\n"
    return raw_pdf(text.encode("ascii"), trailer=trailer)


def kerned_pdf(first: str, second: str, offset: int) -> bytes:
    """One line, one `TJ` array: `first` then `second`, with no drawn space
    glyph between them -- only the numeric `offset` (thousandths of a text
    space unit; negative widens the gap) pdfminer's own layout analysis reads
    to decide whether a word break belongs there (§44.5)."""
    content = (
        f"BT\n/F1 12 Tf\n1 0 0 1 {LEFT_MARGIN:.0f} 700 Tm\n"
        f"[({first}){offset}({second})]TJ\nET\n"
    ).encode("ascii")
    return raw_pdf(content)


def tracked_pdf(word: str, tc: float) -> bytes:
    """One word, drawn glyph by glyph with `Tc` character-tracking spacing
    applied between every pair -- no `TJ` offsets, no drawn spaces."""
    content = (
        f"BT\n/F1 12 Tf\n1 0 0 1 {LEFT_MARGIN:.0f} 700 Tm\n"
        f"{tc} Tc\n({word}) Tj\nET\n"
    ).encode("ascii")
    return raw_pdf(content)


COLUMN_X = 400.0


def two_column_pdf(left: list[str], right: list[str]) -> bytes:
    """Two independent text columns positioned with `Tm`, far enough apart
    (`LEFT_MARGIN` vs `COLUMN_X`) that pdfminer's layout analysis places them
    in separate regions -- two `LTTextBox`es, never one phrase across the
    gutter."""
    text = "BT\n/F1 12 Tf\n"
    y = 700
    for line in left:
        text += f"1 0 0 1 {LEFT_MARGIN:.0f} {y} Tm\n({line}) Tj\n"
        y -= int(LINE_GAP)
    y = 700
    for line in right:
        text += f"1 0 0 1 {COLUMN_X:.0f} {y} Tm\n({line}) Tj\n"
        y -= int(LINE_GAP)
    text += "ET\n"
    return raw_pdf(text.encode("ascii"))


REPORT = minimal_pdf([FIRST_LINE, SECOND_LINE])


@pytest.fixture
def ingested(
    case: tuple[StoreConnection, UUID], tmp_path: Path
) -> tuple[StoreConnection, UUID]:
    conn, case_id = case
    [source_id] = admit_pack(
        conn,
        BlobStore(tmp_path / "blobs"),
        case_id=case_id,
        documents=[Document(filename=BoundaryText.of("report.pdf"), data=REPORT)],
    )
    return conn, source_id


def _ingest_pdf(
    conn: StoreConnection, case_id: UUID, tmp_path: Path, data: bytes
) -> UUID:
    """Admit one arbitrary PDF and return its source id.

    A shared helper rather than another fixture: each of the tests below
    builds its own page, so the document is the thing that varies and the
    admission plumbing around it should not be repeated six times.
    """
    [source_id] = admit_pack(
        conn,
        BlobStore(tmp_path / "blobs"),
        case_id=case_id,
        documents=[Document(filename=BoundaryText.of("doc.pdf"), data=data)],
    )
    return source_id


def test_the_extractor_reads_words_with_the_documents_own_coordinates() -> None:
    tokens = PdfExtractor().extract(REPORT)

    assert isinstance(tokens[0], Token)
    assert tokens[0].text == "Total"
    assert tokens[0].x0 == pytest.approx(LEFT_MARGIN, abs=0.5)
    # A rectangle wider than its word would highlight the space beside it.
    assert tokens[0].x1 < tokens[1].x0


def test_lines_are_separate_lines_and_sit_a_line_apart() -> None:
    tokens = PdfExtractor().extract(REPORT)
    first = next(token for token in tokens if token.text == "Total")
    second = next(token for token in tokens if token.text == "Cash")

    assert first.line_id != second.line_id
    # PDF coordinates count up from the bottom of the page, so the second line
    # is lower on the page and smaller in y.
    assert first.y0 - second.y0 == pytest.approx(LINE_GAP, abs=0.5)


def test_a_pdf_that_is_not_a_pdf_is_refused_without_quoting_it() -> None:
    with pytest.raises(Refusal) as caught:
        PdfExtractor().extract(b"%PDF-1.4\nnot really\n")

    assert caught.value.code is RefusalCode.SOURCE_NOT_READABLE
    assert str(caught.value) == RefusalCode.SOURCE_NOT_READABLE.value


def test_the_pdf_extractor_is_an_extractor() -> None:
    """The same seam the plain-text one implements, which is why nothing above
    this module had to change to accept it."""
    extractor: Extractor = PdfExtractor()

    assert extractor.extract(REPORT)


def test_citations_anchor_in_an_extracted_pdf(
    ingested: tuple[StoreConnection, UUID],
) -> None:
    """The named test. A quote from a real page, located by the host, with a
    rectangle the document itself supplied."""
    conn, source_id = ingested

    boxes = anchor_citation(
        conn, source_id=source_id, page=1, matched_text="USD 1,240.0m"
    )

    assert len(boxes) == 1
    box = boxes[0]
    assert box.page == 1
    assert box.x0 < box.x1 and box.y0 < box.y1
    # Not the fixed-pitch fiction the plain-text extractor would have produced:
    # this rectangle starts partway along a real line of type.
    assert box.x0 > LEFT_MARGIN


def test_a_quote_that_wraps_two_lines_of_the_page_gets_two_rectangles(
    ingested: tuple[StoreConnection, UUID],
) -> None:
    """Both lines are one paragraph, so the quote may cross between them -- and
    the result is one rectangle per line, the QuadPoints shape."""
    conn, source_id = ingested

    boxes = anchor_citation(
        conn,
        source_id=source_id,
        page=1,
        matched_text="USD 1,240.0m Cash and equivalents",
    )

    assert len(boxes) == 2
    assert boxes[0].y0 != boxes[1].y0


def test_a_quote_that_is_not_on_the_page_is_refused(
    ingested: tuple[StoreConnection, UUID],
) -> None:
    conn, source_id = ingested

    with pytest.raises(Refusal) as caught:
        anchor_citation(conn, source_id=source_id, page=1, matched_text="USD 9,999.9m")

    assert caught.value.code is RefusalCode.CITATION_NOT_LOCATED


def test_words_separated_by_positioning_are_separate_tokens() -> None:
    """`§44.5`: pdfminer's own layout analysis, not a custom heuristic, decides
    a word break. A `TJ` array can draw two words with no space glyph between
    them at all -- only a wide enough numeric offset -- and that offset alone
    must still produce two tokens, not one run of concatenated letters."""
    tokens = PdfExtractor().extract(kerned_pdf("Alpha", "Beta", -1000))

    assert [token.text for token in tokens] == ["Alpha", "Beta"]
    assert tokens[0].x1 < tokens[1].x0


def test_tracked_glyphs_within_word_margin_form_one_token() -> None:
    """`Tc` character tracking spreads every glyph of a word, including the
    ones inside it -- a real PDF a designer tracked for readability. The gaps
    it introduces stay under pdfminer's `word_margin` threshold, so pdfminer
    inserts no word break and the word is still one token."""
    tokens = PdfExtractor().extract(tracked_pdf("Hello", 0.5))

    assert len(tokens) == 1
    assert tokens[0].text == "Hello"


def test_widely_spaced_glyphs_refuse_the_joined_quote(
    case: tuple[StoreConnection, UUID], tmp_path: Path
) -> None:
    """The failure mode the fix closes: before it, `Alpha` and `Beta` above
    would have merged into one token `AlphaBeta`, and a module citing that
    concatenation -- text that appears nowhere on the rendered page -- would
    have been honoured. Split into two tokens, that quote is not there."""
    conn, case_id = case
    source_id = _ingest_pdf(conn, case_id, tmp_path, kerned_pdf("Alpha", "Beta", -1000))

    with pytest.raises(Refusal) as caught:
        anchor_citation(conn, source_id=source_id, page=1, matched_text="AlphaBeta")

    assert caught.value.code is RefusalCode.CITATION_NOT_LOCATED


LEFT_COLUMN = ["North region posted strong growth", "in the fourth quarter alone"]
RIGHT_COLUMN = ["South region held steady margins", "through the same period instead"]


def test_a_quote_wrapping_within_a_column_gets_one_rectangle_per_line(
    case: tuple[StoreConnection, UUID], tmp_path: Path
) -> None:
    """Two independent columns on the page, and the quote still wraps cleanly
    within the one it lives in -- the region grouping that makes a column a
    column is what lets a quote cross a line inside it at all."""
    conn, case_id = case
    source_id = _ingest_pdf(
        conn, case_id, tmp_path, two_column_pdf(LEFT_COLUMN, RIGHT_COLUMN)
    )

    boxes = anchor_citation(
        conn, source_id=source_id, page=1, matched_text="growth in the fourth"
    )

    assert len(boxes) == 2
    assert boxes[0].y0 != boxes[1].y0


def test_a_quote_across_the_column_gutter_is_not_located(
    case: tuple[StoreConnection, UUID], tmp_path: Path
) -> None:
    """`alone` ends the left column's second line and `South` opens the right
    column's first -- adjacent in the token stream, on the same row of the
    page, and never a phrase: they are two regions, and invariant 11 never
    assembles a quote across that gutter."""
    conn, case_id = case
    source_id = _ingest_pdf(
        conn, case_id, tmp_path, two_column_pdf(LEFT_COLUMN, RIGHT_COLUMN)
    )

    with pytest.raises(Refusal) as caught:
        anchor_citation(conn, source_id=source_id, page=1, matched_text="alone South")

    assert caught.value.code is RefusalCode.CITATION_NOT_LOCATED


def test_a_quote_repeated_on_the_page_is_ambiguous(
    case: tuple[StoreConnection, UUID], tmp_path: Path
) -> None:
    """Ambiguity is counted over the whole page (§44.5): the same sentence
    drawn twice gives the host two equally good matches and no way to choose
    between them, so it refuses rather than silently picking the first."""
    conn, case_id = case
    repeated = minimal_pdf(["Confirmed total figure", "Confirmed total figure"])
    source_id = _ingest_pdf(conn, case_id, tmp_path, repeated)

    with pytest.raises(Refusal) as caught:
        anchor_citation(
            conn, source_id=source_id, page=1, matched_text="Confirmed total"
        )

    assert caught.value.code is RefusalCode.CITATION_AMBIGUOUS
