"""Generate the reviewed canonical-adapter identity pin."""

from __future__ import annotations

import sys
from hashlib import sha256
from importlib import import_module
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

adapter_manifest_bytes = import_module(
    "server.methodology.adapter_identity"
).adapter_manifest_bytes


def generate_adapter_pin(root: Path = ROOT) -> str:
    """Write only the compiled expected digest, never an input to its own hash."""
    digest = sha256(adapter_manifest_bytes()).hexdigest()
    (root / "server/methodology/adapter_pin.py").write_text(
        '"""Generated by scripts/canonical_adapter_manifest.py; do not edit."""\n\n'
        "CANONICAL_ADAPTER_SHA256 = (\n"
        f'    "{digest}"\n'
        ")\n",
        encoding="utf-8",
    )
    return digest


if __name__ == "__main__":
    generate_adapter_pin()
