"""Generate the CP-CF authority manifest and its compiled pin; never edit vendor."""

from hashlib import sha256
from json import dumps
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def generate_host_manifest(root: Path = ROOT) -> bytes:
    """Exact skill/calculator source digests, in the vendor's record shape."""
    files = {
        "SKILL.md": root / "methodology/skills/cp-cf/SKILL.md",
        "scripts/cash_flow.py": root / "server/calculators/cash_flow.py",
    }
    hashes = {}
    for name, path in files.items():
        data = path.read_bytes()
        hashes[name] = {"bytes": len(data), "sha256": sha256(data).hexdigest()}
    return (
        dumps(
            {"module_id": "CP-CF", "relative_file_hashes": hashes},
            sort_keys=True,
            indent=2,
        )
        + "\n"
    ).encode()


if __name__ == "__main__":
    raw = generate_host_manifest()
    (ROOT / "methodology/skills/HOST_INTEGRITY_v1.json").write_bytes(raw)
    (ROOT / "server/methodology/host_pin.py").write_text(
        '"""Generated by scripts/host_manifest.py; host route identity."""\n\n'
        + 'HOST_MANIFEST_SHA256 = (\n    "'
        + sha256(raw).hexdigest()
        + '"\n)\n'
    )
